"""场景模板库：对话式沙盒模拟训练的全部场景模板。

原 7 个模板自 brain_of_cloud.services.sandbox 迁移而来（template_id 完全一致），
新增 18 个场景覆盖应急处置/文化礼仪/接待服务/遗产讲解/风貌讲解/主题讲解/带团实战/服务规范/特殊游客等类别。

类型定义一律从 brain_of_cloud.services.sandbox 导入，不在此重复定义。
"""

from __future__ import annotations

from brain_of_cloud.services.sandbox import CustomerProfile, SandboxStage, SandboxTemplate

# ══════════════════════════ 场景模板 ══════════════════════════

TEMPLATES: list[SandboxTemplate] = [
# ── 入境定制游全流程实战（fullflow）· 与技能树「入境游实战能力」行前/行中/行后对应 ──
    SandboxTemplate(
        template_id="t_pre_l1",
        mode="fullflow",
        title="行前第1课 · 需求挖掘访谈",
        location="定制游线上咨询",
        task="对一位潜在入境客户做需求访谈：破冰、按维度追问、识别禁忌健康，产出结构化需求卡雏形。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="一位海外客户刚提交咨询，需求模糊。这是行前第一节：学会把模糊期待问成可设计的订单。",
        situation="你是潜在客户，想法模糊，会观察定制师是否耐心专业再决定是否透露真实想法。",
        stages=[
            SandboxStage(
                title="行前课① 破冰与分维度提问",
                objective="开场破冰并按一个维度一次地问，收集场景/同伴/偏好/节奏信息。",
                guide_hint="先问候说明来意，一次只问一个维度；对方犹豫给选项。",
                kb_keywords=[
                    "行前·访谈：开场破冰与建立安全感的话术",
                    "行前·访谈：一次只问一个维度的提问纪律",
                    "行前·访谈：追问出行场景（家人朋友独自/庆祝节点）",
                    "行前·访谈：追问兴趣偏好（自然人文美食/排除项）"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行前课② 禁忌健康与需求卡确认",
                objective="识别禁忌/健康/特殊需求，并把访谈整理成需求卡复述确认。",
                guide_hint="主动问宗教饮食禁忌与过敏健康，覆盖老人/儿童/无障碍等；复述需求卡请客户确认。",
                kb_keywords=[
                    "行前·访谈：宗教饮食禁忌主动询问清单（伊斯兰/犹太/印度教/佛教）",
                    "行前·访谈：过敏与健康需求识别（过敏原/用药/慢性病）",
                    "行前·需求卡：把访谈内容整理成结构化需求卡的步骤",
                    "行前·需求卡：必填字段清单（人数天数预算偏好禁忌）"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.3),
                    ("互动引导", 1.2)
        ],
        customer_pool=[
            CustomerProfile(
                name="Emma", nationality="美国", age="28",
                personality="活泼直率，对服务细节敏感",
                preferences="偏爱自然与在地美食",
                quirks="说话快，爱一次抛几个问题",
                hidden="蜜月旅行，想要惊喜",
            ),
            CustomerProfile(
                name="Jack", nationality="澳大利亚", age="34",
                personality="务实高效",
                preferences="商务顺带城市体验",
                quirks="爱确认时间点",
                hidden="实际只有两天完整时间",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_pre_l2",
        mode="fullflow",
        title="行前第2课 · 免签240小时行程设计",
        location="定制师工作台",
        task="基于需求卡设计免签240小时合规行程：模块拆分、线路串联、停留与出入境口径核对。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="客户需求已确认。这一课把需求变成一条合规、可走的 240 小时免签行程。",
        situation="你是已确认需求的客户，期待一条不用太赶、又能深入体验的线路，会留意导游是否讲得清政策边界。",
        stages=[
            SandboxStage(
                title="设计课① 需求转模块",
                objective="把需求卡拆成交通/住宿/活动/讲解模块并组合成线路。",
                guide_hint="按需求拆模块，先粗后细；节奏上紧凑与留白平衡。",
                kb_keywords=[
                    "行前·设计：行程模块拆分的总体原则",
                    "行前·设计：交通与住宿模块的设计要点",
                    "行前·设计：活动与讲解模块的设计要点",
                    "行前·设计：模块组合与行程节奏的注意事项"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="设计课② 240h合规核对",
                objective="核对免签240h适用范围、停留时间计算与出入境口径，给出证件材料提示。",
                guide_hint="讲清240h政策要点与计算口径，核对出入境与停留天数，提示证件材料。",
                kb_keywords=[
                    "行前·设计：免签240小时的政策要点与适用范围",
                    "行前·设计：免签240小时的停留时间计算与出入境核对",
                    "行前·设计：免签240小时经典城市线路设计",
                    "行前·设计：免签行程的证件与材料准备"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("文化知识", 1.3),
                    ("表达能力", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Emma", nationality="美国", age="28",
                personality="活泼直率，对服务细节敏感",
                preferences="偏爱自然与在地美食",
                quirks="说话快，爱一次抛几个问题",
                hidden="蜜月旅行，想要惊喜",
            ),
            CustomerProfile(
                name="Jack", nationality="澳大利亚", age="34",
                personality="务实高效",
                preferences="商务顺带城市体验",
                quirks="爱确认时间点",
                hidden="实际只有两天完整时间",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_pre_l3",
        mode="fullflow",
        title="行前第3课 · 报价与行程单",
        location="定制师工作台",
        task="对行程做透明模块化报价并交付颗粒度达标的行程单，定定金规则并促成下单。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="线路已定。这一课把方案变成一张看得懂、敢下定的单。",
        situation="你是满意的客户，对价格透明与信息细节敏感，需要明确的定金与取消规则才放心。",
        stages=[
            SandboxStage(
                title="报价课① 透明报价",
                objective="按模块透明报价，无隐藏费用，讲清支付与定金规则。",
                guide_hint="模块化口径报价，透明度优先；说明汇率与支付/定金/有效期。",
                kb_keywords=[
                    "行前·报价：模块化报价的组成与口径",
                    "行前·报价：报价单透明度与隐藏费用避让",
                    "行前·报价：支付方式与定金规则",
                    "行前·报价：报价有效期与留价策略"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="报价课② 行程单交付",
                objective="交付含体能/健康/宗教饮食/交通/天气字段的行程单并促成确认。",
                guide_hint="按国际颗粒度填字段（海拔/难度/过敏原/车程等），请客户确认下单。",
                kb_keywords=[
                    "行前·行程单：信息颗粒度的自查清单",
                    "行前·行程单：体能字段（海拔/步行距离/难度等级）的填写",
                    "行前·行程单：健康字段（过敏原/无障碍/医疗设施）的填写",
                    "行前·行程单：交通字段（车程/换乘/接送说明）的填写"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.2),
                    ("表达能力", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Emma", nationality="美国", age="28",
                personality="活泼直率，对服务细节敏感",
                preferences="偏爱自然与在地美食",
                quirks="说话快，爱一次抛几个问题",
                hidden="蜜月旅行，想要惊喜",
            ),
            CustomerProfile(
                name="Jack", nationality="澳大利亚", age="34",
                personality="务实高效",
                preferences="商务顺带城市体验",
                quirks="爱确认时间点",
                hidden="实际只有两天完整时间",
            ),
        ],
    ),

    SandboxTemplate(
        template_id="t_ff_pre_trip",
        mode="fullflow",
        title="行前 · 入境定制咨询全流程（免签240小时）",
        location="定制游线上咨询 · 定制师工作台",
        task="承接一位潜在入境客户的定制咨询：完成需求访谈、识别禁忌与健康需求、复述需求卡、设计免签240小时合规行程、交付颗粒度达标的行程单并给出透明报价促成下单。",
        difficulty=3,
        category="入境定制游全流程实战",
        opening="一位海外客户通过平台提交了定制咨询。系统提示：这是你承接入境定制游的一单，客户对中国免签政策有初步了解，想趁240小时免签窗口来一次深度体验，但需求还很模糊，需要你一步步引导。",
        situation="你是一位正在考虑来中国旅行的海外游客，对目的地只有模糊期待，想找一位靠谱的定制师帮你把想法变成具体行程。你会先观察定制师是否专业、是否耐心，再决定要不要透露真实预算和诉求。",
        stages=[
            SandboxStage(
                title="行前 ① 开场破冰与安全感",
                objective="开场破冰、自我介绍并说明定制服务流程，征得同意后再开始访谈，让客户愿意开口说真实需求。",
                guide_hint="先问候建立初步接触，再自我介绍、说明来意与定制流程，最后征得同意再进入访谈；不要一上来就连环追问。",
                kb_keywords=[
                    "行前·访谈：开场破冰与建立安全感的话术",
                    "行前·访谈：一次只问一个维度的提问纪律",
                    "行前·访谈：对方犹豫时给选项而非开放式问题",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行前 ② 分维度需求访谈",
                objective="按出行场景、同伴构成、兴趣偏好、节奏体力、过往旅行、底线禁忌逐维度访谈，一次只问一个维度，把模糊期待变成可设计的需求。",
                guide_hint="依次了解出行场景（家人朋友独自/庆祝节点）、兴趣偏好（自然人文美食与排除项）、节奏体力（紧凑还是留白）、过往旅行参考（好评差评环节）、底线与禁忌（绝对不去/不能错过）。",
                kb_keywords=[
                    "行前·访谈：追问出行场景（家人朋友独自/庆祝节点）",
                    "行前·访谈：追问兴趣偏好（自然人文美食/排除项）",
                    "行前·访谈：追问节奏与体力（紧凑留白/出发时间）",
                    "行前·访谈：追问过往旅行参考（好评差评环节）",
                    "行前·访谈：追问底线与禁忌（绝对不去/不能错过）",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="行前 ③ 禁忌·健康·特殊需求识别",
                objective="主动询问宗教饮食禁忌、过敏与健康状况，识别老人/儿童/无障碍/商务加旅游等特殊需求并记录，避免后续行程踩雷。",
                guide_hint="按清单主动问宗教饮食禁忌（伊斯兰/犹太/印度教/佛教）、过敏原/用药/慢性病，再覆盖老人、儿童、无障碍、商务加旅游混合需求。",
                kb_keywords=[
                    "行前·访谈：宗教饮食禁忌主动询问清单（伊斯兰/犹太/印度教/佛教）",
                    "行前·访谈：过敏与健康需求识别（过敏原/用药/慢性病）",
                    "行前·访谈：老人游客需求识别要点",
                    "行前·访谈：儿童亲子需求识别要点",
                    "行前·访谈：无障碍出行需求识别要点",
                    "行前·访谈：商务加旅游混合需求记录要点",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行前 ④ 需求卡复述与免签240h行程设计",
                objective="把访谈内容整理成结构化需求卡并向客户复述确认，再按模块拆分设计行程，核对免签240小时政策的停留时间与出入境口径。",
                guide_hint="先输出需求卡必填字段（人数/天数/预算/偏好/禁忌）并请客户二次确认，再按交通住宿/活动讲解模块组合行程，最后核对免签240小时适用范围、停留计算与经典城市线路。",
                kb_keywords=[
                    "行前·需求卡：把访谈内容整理成结构化需求卡的步骤",
                    "行前·需求卡：必填字段清单（人数天数预算偏好禁忌）",
                    "行前·需求卡：与客户二次确认需求卡的注意事项",
                    "行前·设计：行程模块拆分的总体原则",
                    "行前·设计：交通与住宿模块的设计要点",
                    "行前·设计：活动与讲解模块的设计要点",
                    "行前·设计：免签240小时的政策要点与适用范围",
                    "行前·设计：免签240小时的停留时间计算与出入境核对",
                    "行前·设计：免签240小时经典城市线路设计",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="行前 ⑤ 行程单交付与报价促成",
                objective="交付信息颗粒度达标（体能/健康/宗教饮食/交通/天气）的行程单，给出透明模块化报价，明确定金与支付规则并促成下单。",
                guide_hint="按国际分销标准填写海拔/步行距离/难度、过敏原/无障碍/医疗、清真/洁食/素食、车程换乘、天气着装等字段；报价做到模块透明、无隐藏费用，给支付方式与定金规则、报价有效期。",
                kb_keywords=[
                    "行前·行程单：体能字段（海拔/步行距离/难度等级）的填写",
                    "行前·行程单：健康字段（过敏原/无障碍/医疗设施）的填写",
                    "行前·行程单：宗教与饮食字段（清真/洁食/素食）的填写",
                    "行前·行程单：交通字段（车程/换乘/接送说明）的填写",
                    "行前·行程单：天气与着装携带建议字段的填写",
                    "行前·行程单：信息颗粒度的自查清单",
                    "行前·报价：模块化报价的组成与口径",
                    "行前·报价：报价单透明度与隐藏费用避让",
                    "行前·报价：支付方式与定金规则",
                    "行前·报价：报价有效期与留价策略",
                ],
                min_turns=3,
            ),
        ],
        goals=[("服务意识", 1.2), ("互动引导", 1.2), ("表达能力", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="Emma", nationality="美国", age="28",
                personality="活泼直率，喜欢新鲜体验，对服务细节敏感",
                preferences="偏爱自然风光与在地美食，喜欢拍照打卡",
                quirks="说话快，习惯一次性抛出好几个问题",
                hidden="这是蜜月旅行，想留下特别的纪念，希望行程有惊喜感",
            ),
            CustomerProfile(
                name="Jack", nationality="澳大利亚", age="34",
                personality="务实高效，重视时间与性价比",
                preferences="商务出差顺带城市体验，喜欢精酿与夜生活",
                quirks="会反复确认时间点和行程弹性",
                hidden="实际只有两天完整时间，预算不高但不愿显得抠门",
            ),
            CustomerProfile(
                name="Olivia", nationality="英国", age="55",
                personality="优雅克制，注重文化深度与服务分寸",
                preferences="喜欢博物馆、园林与慢节奏游览",
                quirks="对无障碍与步行强度很在意，会追问细节",
                hidden="腿脚略有不便，需要较少步行与充足休整，但不希望被过度照顾",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_mid_l1",
        mode="fullflow",
        title="行中第1课 · 接机核对与破冰",
        location="机场接机口",
        task="完成接机前核对与现场破冰，处理延误/行李/转机衔接等首站小状况。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="客户航班即将落地。这是行中第一节：第一面就把安全感建立起来。",
        situation="你是刚抵达的游客，长途疲惫，期待接机顺利，遇小状况情绪容易波动。",
        stages=[
            SandboxStage(
                title="接机课① 信息核对与迎接",
                objective="核对航班/时间/人数/举牌，见面问候破冰并说明安排。",
                guide_hint="先核落地信息再举牌；见面破冰，讲清接下来安排。",
                kb_keywords=[
                    "行中·接机：接机前信息核对清单（航班/时间/人数/举牌）",
                    "行中·接机：首次见面的问候与破冰话术要点",
                    "行中·接机：接机位置与等待期间的沟通"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="接机课② 首站小状况",
                objective="应对延误/行李/转机衔接中的一种小状况，稳住节奏。",
                guide_hint="延误主动同步，行李引导流程，转机给应急预案。",
                kb_keywords=[
                    "行中·接机：航班延误取消的应对注意事项",
                    "行中·接机：行李丢失的引导处理要点",
                    "行中·接机：转机时间不足的应急处置"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("控场能力", 1.3),
                    ("服务意识", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮",
                quirks="疑问不当场提",
                hidden="对准时与细节要求高",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度高",
                preferences="喜欢夜市夜景",
                quirks="爱拍照发社交媒体",
                hidden="对支付便利敏感",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_mid_l2",
        mode="fullflow",
        title="行中第2课 · 涉外入住与履约",
        location="酒店前台",
        task="协助外宾入住登记，按合规口径处理涉外资格类问题并完成入住告知。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="客人到酒店办理入住。这一课练涉外履约里最常见的合规场景。",
        situation="你是外宾，在意是否被规范对待；若被拒会很不满并质疑服务专业性。",
        stages=[
            SandboxStage(
                title="入住课① 登记与告知",
                objective="核对证件、完成登记，并告知入住注意事项。",
                guide_hint="证件登记要点+入住告知清单，注意行李与小费惯例。",
                kb_keywords=[
                    "行中·衔接：外宾酒店入住的证件与登记要点",
                    "行中·衔接：入住后注意事项告知清单",
                    "行中·衔接：行李搬运与小费惯例"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="入住课② 拒接合规应对",
                objective="若遇“无涉外资格”拒接，按合规口径沟通并给客户定心丸。",
                guide_hint="重申不得以涉外资格拒接，按合规口径处理并留存证据。",
                kb_keywords=[
                    "行中·履约：不得以资质为由拒接外宾的规定",
                    "行中·履约：酒店涉外资格拒接的合规口径",
                    "行中·衔接：酒店被无涉外资格拒接的应对"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.3),
                    ("控场能力", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮",
                quirks="疑问不当场提",
                hidden="对准时与细节要求高",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度高",
                preferences="喜欢夜市夜景",
                quirks="爱拍照发社交媒体",
                hidden="对支付便利敏感",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_mid_l3",
        mode="fullflow",
        title="行中第3课 · 跨文化讲解",
        location="核心讲解点",
        task="按开场-主体-收尾完成一次讲解，结合游客文化背景做互动并避免误解。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="到了今天最重头的讲解点。这一课练把知识讲得对方爱听、听得懂。",
        situation="你是游客，期待讲解有故事有互动；若导游照本宣科或讲错会明显失望。",
        stages=[
            SandboxStage(
                title="讲解课① 结构开场主体",
                objective="按结构开场立期待、主体讲清楚，控制节奏。",
                guide_hint="先给结构再展开，多用互动提问，照顾文化偏好。",
                kb_keywords=[
                    "行中·讲解：讲解结构（开场主体收尾）的设计",
                    "行中·讲解：按技能点准备讲解要点的步骤",
                    "行中·讲解：互动提问与引导技巧"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="讲解课② 文化适配与纠偏",
                objective="结合游客文化背景调整表达，出现误解当场化解。",
                guide_hint="用对方熟悉的锚点打比方；讲错当场纠正，误解现场化解。",
                kb_keywords=[
                    "行中·讲解：欧美游客的讲解偏好",
                    "行中·讲解：文化误解现场的化解话术",
                    "行中·讲解：讲解内容的准确性核查"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("文化知识", 1.4),
                    ("互动引导", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮",
                quirks="疑问不当场提",
                hidden="对准时与细节要求高",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度高",
                preferences="喜欢夜市夜景",
                quirks="爱拍照发社交媒体",
                hidden="对支付便利敏感",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_mid_l4",
        mode="fullflow",
        title="行中第4课 · 支付预约与数字工具",
        location="行程中（餐厅/景区/车上）",
        task="处理外卡支付失败、景区预约与境外App访问受阻等履约小摩擦。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="行程中总有小摩擦。这一课专练支付、预约、数字这三类最常见的“劝退点”。",
        situation="你是游客，遇到刷卡失败或订票不畅会焦虑，需要清晰替代方案。",
        stages=[
            SandboxStage(
                title="摩擦课① 支付与预约",
                objective="外卡失败先安抚再给替代；预约讲清护照号字段与周期风险。",
                guide_hint="解释失败原因并给替代支付；预约用护照号字段、预留风险预案。",
                kb_keywords=[
                    "行中·支付：外卡刷卡失败的常见原因",
                    "行中·支付：支付失败现场的安抚与解决",
                    "行中·预约：景区预约的护照号证件字段填写",
                    "行中·预约：预约周期短的风险预案"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="摩擦课② 数字与替代方案",
                objective="境外常用App不可直连时给上网/替代方案并协助。",
                guide_hint="给eSIM/热点等上网方案，协助注册替代工具，不冷场。",
                kb_keywords=[
                    "行中·数字：Google与WhatsApp不可直连的替代方案",
                    "行中·数字：国际游客上网的解决方案（eSIM/热点）",
                    "行中·数字：APP注册实名绑卡的协助注意事项"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("控场能力", 1.3),
                    ("服务意识", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮",
                quirks="疑问不当场提",
                hidden="对准时与细节要求高",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度高",
                preferences="喜欢夜市夜景",
                quirks="爱拍照发社交媒体",
                hidden="对支付便利敏感",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_mid_l5",
        mode="fullflow",
        title="行中第5课 · 突发应急",
        location="行程途中",
        task="应对一种突发（疾病/证件财物/投诉升级），按流程处置并保住信任。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="突发随时可能来。这一课练在压力下先稳住人、再按流程办。",
        situation="你遇到突发状况，情绪紧张，需要导游冷静专业地接手。",
        stages=[
            SandboxStage(
                title="应急课① 先控场再处置",
                objective="先安抚情绪、评估风险，再按正确流程启动处置。",
                guide_hint="先控场安抚再按流程：疾病找专业急救、证件走挂失等。",
                kb_keywords=[
                    "行中·应急：现场投诉升级的降火话术",
                    "行中·应急：游客突发疾病的处置流程",
                    "行中·应急：护照丢失的挂失补办流程"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="应急课② 收尾与上报",
                objective="完成处置、做好记录与告知，明确上报边界。",
                guide_hint="处理后跟进告知、规范记录，超权限及时上报转交。",
                kb_keywords=[
                    "行中·应急：投诉记录的规范留存",
                    "行中·应急：上报与转交的边界注意事项",
                    "行中·应急：行程被迫中断的退款与补偿口径"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("控场能力", 1.4),
                    ("服务意识", 1.0)
        ],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮",
                quirks="疑问不当场提",
                hidden="对准时与细节要求高",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度高",
                preferences="喜欢夜市夜景",
                quirks="爱拍照发社交媒体",
                hidden="对支付便利敏感",
            ),
        ],
    ),

    SandboxTemplate(
        template_id="t_ff_mid_trip",
        mode="fullflow",
        title="行中 · 入境落地接待全流程",
        location="上海 · 定制游落地接待（接机—酒店—行程中）",
        task="接待一位按定制行程入境的客户：完成接机核对与破冰、涉外入住履约、行程中的讲解与互动、处理支付/预约/数字类小摩擦，并稳妥处置一次突发应急。",
        difficulty=3,
        category="入境定制游全流程实战",
        opening="客户按定制行程抵达上海。系统提示：这是行中全流程的第一站——你已提前拿到航班信息，正举着接机牌在国际到达出口等待。之后的行程里，客户会在入住、游览、支付和一次突发状况中不断考验你的专业度。",
        situation="你是一位刚抵达中国的入境游客，坐了长途航班有些疲惫，对陌生的环境既期待又警惕。你会观察导游是否准备充分、安排是否顺畅，遇到小状况时情绪容易波动，需要被及时安抚。",
        stages=[
            SandboxStage(
                title="行中 ① 接机核对与破冰",
                objective="提前核对航班/时间/人数/举牌，见面问候破冰建立好感；若遇延误、行李或转机衔接问题，给出清晰安排。",
                guide_hint="先核对航班实际落地时间与人数再举牌；见面先问候破冰，说明接下来安排；延误要主动同步信息，行李问题引导按流程处理，转机时间不足要有应急预案。",
                kb_keywords=[
                    "行中·接机：接机前信息核对清单（航班/时间/人数/举牌）",
                    "行中·接机：航班延误取消的应对注意事项",
                    "行中·接机：首次见面的问候与破冰话术要点",
                    "行中·接机：转机时间不足的应急处置",
                    "行中·接机：行李丢失的引导处理要点",
                    "行中·接机：换乘交通的衔接与告知",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行中 ② 涉外入住与履约",
                objective="协助外宾办理入住登记；若遇酒店以涉外资格为由拒接，按合规口径处理；告知入住注意事项与次日安排。",
                guide_hint="外宾入住要核对证件登记并说明注意事项；酒店不得以缺涉外资格拒接外宾，遇到拒接先按合规口径沟通，必要时留存证据并给客户吃定心丸。",
                kb_keywords=[
                    "行中·衔接：外宾酒店入住的证件与登记要点",
                    "行中·衔接：酒店被无涉外资格拒接的应对",
                    "行中·履约：酒店涉外资格拒接的合规口径",
                    "行中·履约：不得以资质为由拒接外宾的规定",
                    "行中·衔接：入住后注意事项告知清单",
                    "行中·衔接：行李搬运与小费惯例",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行中 ③ 讲解与跨文化互动",
                objective="在核心点位按开场—主体—收尾完成讲解，结合客户文化背景做互动提问，避免文化误解。",
                guide_hint="讲解前按技能点备好要点，结构上开场立期待、主体讲清楚、收尾留回味；根据欧美/日韩等客群偏好调整节奏，多用提问互动，讲错了要敢于当场纠正。",
                kb_keywords=[
                    "行中·讲解：按技能点准备讲解要点的步骤",
                    "行中·讲解：讲解结构（开场主体收尾）的设计",
                    "行中·讲解：互动提问与引导技巧",
                    "行中·讲解：讲解内容的准确性核查",
                    "行中·讲解：欧美游客的讲解偏好",
                    "行中·讲解：日韩游客的讲解偏好",
                    "行中·讲解：文化误解现场的化解话术",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="行中 ④ 履约小摩擦（支付/预约/数字）",
                objective="处理行程中常见小摩擦：外卡支付失败、景区预约、网络与境外APP访问受阻，稳住客户情绪并给出可执行的替代方案。",
                guide_hint="外卡失败先安抚并解释原因，再引导替代支付；预约字段要用护照号、预留周期不足的风险要提前预案；境外常用工具不可直连时给eSIM/热点等替代并协助注册。",
                kb_keywords=[
                    "行中·支付：外卡刷卡失败的常见原因",
                    "行中·支付：引导游客使用替代支付方式的要点",
                    "行中·支付：支付失败现场的安抚与解决",
                    "行中·预约：景区预约的护照号证件字段填写",
                    "行中·预约：预约周期短的风险预案",
                    "行中·数字：Google与WhatsApp不可直连的替代方案",
                    "行中·数字：国际游客上网的解决方案（eSIM/热点）",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行中 ⑤ 突发应急收尾",
                objective="应对一次突发状况（游客身体不适/证件或财物问题/投诉升级），按应急处置流程处理并保住客户信任，为行后回访留下好印象。",
                guide_hint="突发状况先控场安抚再按流程处置：疾病先找专业急救并协调送医，护照丢失走挂失补办，投诉升级用降火话术并记录、按边界上报。",
                kb_keywords=[
                    "行中·应急：游客突发疾病的处置流程",
                    "行中·应急：常见急症识别（中暑/食物中毒/心脏问题）",
                    "行中·应急：急救电话与国际救援协调要点",
                    "行中·应急：护照丢失的挂失补办流程",
                    "行中·应急：行李财物丢失的报案与协助",
                    "行中·应急：现场投诉升级的降火话术",
                    "行中·应急：上报与转交的边界注意事项",
                ],
                min_turns=2,
            ),
        ],
        goals=[("控场能力", 1.3), ("文化知识", 1.1), ("服务意识", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="Yuki", nationality="日本", age="42",
                personality="礼貌克制，注重规则与分寸，情绪不外露",
                preferences="喜欢历史建筑与精致餐饮，作息规律",
                quirks="疑问不会当场提出，常在心里记下",
                hidden="对行程准时与细节完整度要求很高，若有纰漏会直接给差评",
            ),
            CustomerProfile(
                name="Lena", nationality="德国", age="38",
                personality="理性直接，重视信息透明与守时",
                preferences="喜欢博物馆与工业遗产，习惯提前确认计划",
                quirks="爱核对时间表，问题具体尖锐",
                hidden="商务考察为主，顺带两日城市体验，行程冲突会让合作方失望",
            ),
            CustomerProfile(
                name="Marcus", nationality="美国", age="45",
                personality="开朗健谈，包容度较高，喜欢互动",
                preferences="喜欢美食夜市与城市夜景",
                quirks="爱拍照发社交媒体，喜欢被介绍背景故事",
                hidden="对支付便利度敏感，外卡刷不了会影响整段行程评价",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_post_l1",
        mode="fullflow",
        title="行后第1课 · 回访与意见收集",
        location="行程结束后（线上回访）",
        task="在合适时机发起回访，收集真实体验并识别潜在不满与改进点。",
        difficulty=1,
        category="入境定制游全流程实战",
        opening="客人已回国。行后第一节：一次好的回访是口碑的开始。",
        situation="你是刚回国的游客，整体不错但有一两个小遗憾，想看看对方是否在乎反馈。",
        stages=[
            SandboxStage(
                title="回访课① 时机与开场",
                objective="选对时机回访，先感谢再收集意见。",
                guide_hint="48h内、情绪满意时回访，先谢后问，开放式引导。",
                kb_keywords=[
                    "行后·信用：行程结束后的回访话术与时机",
                    "行后·客诉：48小时内回访的注意事项",
                    "行后·信用：回访收集改进意见的要点"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.3),
                    ("互动引导", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="James", nationality="英国", age="52",
                personality="温和有礼",
                preferences="深度文化游",
                quirks="会认真写长评",
                hidden="有一处衔接不满",
            ),
            CustomerProfile(
                name="Michael", nationality="美国", age="47",
                personality="直接果断",
                preferences="看重响应速度",
                quirks="发现问题要说法",
                hidden="对一次支付不畅不满",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_post_l2",
        mode="fullflow",
        title="行后第2课 · 客诉处理",
        location="线上客诉",
        task="按受理-共情-补偿节奏处理客诉，分级判断并守住不承诺过头红线。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="客人提出不满。这一课练把差评风险转成好感的机会。",
        situation="你有一处不满，情绪不高，想看看对方是否真诚处理。",
        stages=[
            SandboxStage(
                title="客诉课① 受理与共情",
                objective="先听完再回应，共情安抚，把问题问清楚。",
                guide_hint="先听后说，共情话术，判断轻中重。",
                kb_keywords=[
                    "行后·客诉：投诉受理的标准响应流程",
                    "行后·客诉：安抚情绪的共情话术要点",
                    "行后·客诉：投诉分级标准（轻中重）"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="客诉课② 补偿与边界",
                objective="给到边界的补偿方案，不承诺过头，超权限上报。",
                guide_hint="先听后给、给到边界；守红线；超权限升级留存记录。",
                kb_keywords=[
                    "行后·客诉：先听后给的补偿节奏",
                    "行后·客诉：补偿方案的种类与边界",
                    "行后·客诉：避免承诺过头的红线",
                    "行后·客诉：升级上报流程与权限边界"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.4)
        ],
        customer_pool=[
            CustomerProfile(
                name="James", nationality="英国", age="52",
                personality="温和有礼",
                preferences="深度文化游",
                quirks="会认真写长评",
                hidden="有一处衔接不满",
            ),
            CustomerProfile(
                name="Michael", nationality="美国", age="47",
                personality="直接果断",
                preferences="看重响应速度",
                quirks="发现问题要说法",
                hidden="对一次支付不畅不满",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_post_l3",
        mode="fullflow",
        title="行后第3课 · 好评与平台信用",
        location="线上运营",
        task="在合规前提下引导满意客户留好评，完善listing与信用资产。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="客人满意了。这一课把满意度变成海外平台上看得见的信用。",
        situation="你是满意客户，愿意好评但不想被“索评”打扰，讲究自然。",
        stages=[
            SandboxStage(
                title="信用课① 合规引导好评",
                objective="在合适时机用合规话术引导留评。",
                guide_hint="满意且情绪高点再提；不索评不诱导，给简化路径。",
                kb_keywords=[
                    "行后·信用：合规的好评引导话术（避免索评违规）",
                    "行后·信用：提留评的适当时机",
                    "行后·信用：留评流程简化的操作建议"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="信用课② listing完善",
                objective="完善TripAdvisor/Google listing信息与照片标签。",
                guide_hint="补全listing信息与照片描述，注意回复率影响。",
                kb_keywords=[
                    "行后·信用：TripAdvisor的listing信息完善要点",
                    "行后·信用：Google商家listing信息完善要点",
                    "行后·信用：回复率与响应速度对排名的影响"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.2),
                    ("表达能力", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="James", nationality="英国", age="52",
                personality="温和有礼",
                preferences="深度文化游",
                quirks="会认真写长评",
                hidden="有一处衔接不满",
            ),
            CustomerProfile(
                name="Michael", nationality="美国", age="47",
                personality="直接果断",
                preferences="看重响应速度",
                quirks="发现问题要说法",
                hidden="对一次支付不畅不满",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_post_l4",
        mode="fullflow",
        title="行后第4课 · 复购与转介绍",
        location="线上回访",
        task="识别复购信号、给老客户权益，并在合适时机开口请转介绍。",
        difficulty=2,
        category="入境定制游全流程实战",
        opening="一次满意的旅程结束，生意其实才刚开始。这一课练把客人变回头客与口碑源。",
        situation="你是满意客户，正考虑带家人再来，也愿意推荐给朋友。",
        stages=[
            SandboxStage(
                title="复购课① 识别机会与权益",
                objective="从回访中识别复购信号，给老客户专属权益。",
                guide_hint="捕捉“下次/家人/商务”信号，给专属优惠并维护档案。",
                kb_keywords=[
                    "行后·复购：识别复购机会的信号",
                    "行后·复购：老客户专属优惠的给法",
                    "行后·复购：客户关系档案的维护要点"
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="复购课② 转介绍开口",
                objective="在合适时机合规开口请转介绍。",
                guide_hint="满意基础上自然开口，激励合规设计。",
                kb_keywords=[
                    "行后·转介：开口请转介绍的时机与话术",
                    "行后·转介：转介绍激励的合规设计",
                    "行后·转介：把好评客户变成口碑源头的要点"
                ],
                min_turns=2,
            ),
        ],
        goals=[
                    ("服务意识", 1.3),
                    ("互动引导", 1.1)
        ],
        customer_pool=[
            CustomerProfile(
                name="James", nationality="英国", age="52",
                personality="温和有礼",
                preferences="深度文化游",
                quirks="会认真写长评",
                hidden="有一处衔接不满",
            ),
            CustomerProfile(
                name="Michael", nationality="美国", age="47",
                personality="直接果断",
                preferences="看重响应速度",
                quirks="发现问题要说法",
                hidden="对一次支付不畅不满",
            ),
        ],
    ),

    SandboxTemplate(
        template_id="t_ff_post_trip",
        mode="fullflow",
        title="行后 · 回访复购全流程",
        location="行程结束后 · 客户已回国（线上回访）",
        task="客户结束定制游回国后，在合适时机发起回访并收集意见、妥善处理客诉，合规引导平台好评与listing信用建设，识别复购与转介绍机会。",
        difficulty=3,
        category="入境定制游全流程实战",
        opening="客户的定制游已结束并平安回国。系统提示：行后服务才是口碑的开始——你需要在合适的时机发起回访，把这次体验转化为平台好评、复购和转介绍，同时把可能的差评风险提前化解。",
        situation="你是一位刚结束中国定制游回国的游客，行程总体不错但有一两个小遗憾。你希望有人认真听听你的感受；若处理得好，你会考虑再来或推荐给朋友，处理不好则可能留下差评。",
        stages=[
            SandboxStage(
                title="行后 ① 回访开场与意见收集",
                objective="选对时机发起回访，先感谢再收集全程体验意见，识别客户潜在不满与改进点。",
                guide_hint="回访先问候感谢、说明来意，让对方愿意开口；围绕行程亮点与槽点收集意见，重点捕捉客户没说出口的不满信号。",
                kb_keywords=[
                    "行后·信用：行程结束后的回访话术与时机",
                    "行后·信用：回访收集改进意见的要点",
                    "行后·客诉：48小时内回访的注意事项",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行后 ② 客诉处理",
                objective="若客户提出不满或差评，按受理—共情—补偿节奏处理，分级判断是否上报，守住不承诺过头的红线。",
                guide_hint="先听完再回应，用共情话术安抚情绪；按轻中重分级，补偿先听后给、给到边界为止；超权限的升级上报并留存记录。",
                kb_keywords=[
                    "行后·客诉：投诉受理的标准响应流程",
                    "行后·客诉：投诉分级标准（轻中重）",
                    "行后·客诉：安抚情绪的共情话术要点",
                    "行后·客诉：先听后给的补偿节奏",
                    "行后·客诉：补偿方案的种类与边界",
                    "行后·客诉：避免承诺过头的红线",
                    "行后·客诉：升级上报流程与权限边界",
                    "行后·客诉：TripAdvisor差评的回应模板",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="行后 ③ 好评留评与平台信用",
                objective="在合规前提下引导满意客户留好评、完善listing与照片标签，提升TripAdvisor/Google等平台的信用资产。",
                guide_hint="选客户满意度最高、情绪最好的时机提留评，话术要合规不索评；同步引导完善listing信息与照片描述标签，注意回复率与响应速度对排名的影响。",
                kb_keywords=[
                    "行后·信用：合规的好评引导话术（避免索评违规）",
                    "行后·信用：提留评的适当时机",
                    "行后·信用：留评流程简化的操作建议",
                    "行后·信用：TripAdvisor的listing信息完善要点",
                    "行后·信用：Google商家listing信息完善要点",
                    "行后·信用：照片描述标签优化的注意事项",
                    "行后·信用：回复率与响应速度对排名的影响",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="行后 ④ 复购与转介绍",
                objective="识别客户的复购信号与下次来华计划，给老客户专属权益，并在合适时机开口请转介绍、合规设计激励。",
                guide_hint="从回访中识别复购信号（提到下次/家人/商务需求），给老客户专属优惠并维护客户档案；满意客户在合适时机开口请转介绍，激励设计要合规。",
                kb_keywords=[
                    "行后·复购：识别复购机会的信号",
                    "行后·复购：老客户专属优惠的给法",
                    "行后·复购：客户关系档案的维护要点",
                    "行后·转介：开口请转介绍的时机与话术",
                    "行后·转介：转介绍激励的合规设计",
                    "行后·转介：把好评客户变成口碑源头的要点",
                ],
                min_turns=2,
            ),
        ],
        goals=[("服务意识", 1.3), ("互动引导", 1.1), ("表达能力", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="James", nationality="英国", age="52",
                personality="温和有礼，愿意分享真实感受",
                preferences="喜欢深度文化游，重视服务细节",
                quirks="会认真写长评，也乐于推荐给朋友",
                hidden="整体满意，但觉得行中有一处衔接不够顺畅，想看看你们是否在乎客户反馈",
            ),
            CustomerProfile(
                name="Michael", nationality="美国", age="47",
                personality="直接果断，不藏着掖着",
                preferences="看重性价比与响应速度",
                quirks="发现问题当场就要说法",
                hidden="对行程中一次支付不畅很不满，若回访不到位会直接去平台写差评",
            ),
            CustomerProfile(
                name="Sarah", nationality="澳大利亚", age="31",
                personality="热情外向，喜欢分享旅行故事",
                preferences="蜜月旅行，喜欢拍照与美食",
                quirks="朋友圈影响力强，爱发攻略",
                hidden="体验超出预期，正在计划带父母再来，是最好的复购与转介绍对象",
            ),
        ],
    ),

    SandboxTemplate(
        template_id="t_ff_culture_bridge",
        mode="fullflow",
        title="入境定制游 · 文化桥搭建训练",
        location="定制行程途中 · 讲解点/餐厅/车厢等相处场景",
        task="在入境定制游的行程相处中，主动识别游客所属国家的文化背景，用中国与该国文化的共同点搭建「文化桥」，增强好感与信任，同时把沟通风格、礼仪或禁忌上的差异风险提前化解。",
        difficulty=3,
        category="入境定制游全流程实战",
        opening="你正带着一位入境游客进行定制行程。系统提示：跨文化接待的加分项不是背差异清单，而是会「搭桥」——把中国文化里和对方相通的部分讲出来，让对方觉得亲切、被理解。请在相处中抓住机会自然搭建文化桥，并把可能的敏感点提前化解。",
        situation="你是一位来中国定制游的海外游客，对中国文化好奇，但也有很多差异带来的困惑与防备。如果导游能主动讲出与你家乡相通的地方（家庭、节庆、饮食、勤奋、待客），你会很快亲近信任；如果只讲差异、生硬说教，你会礼貌疏远。",
        stages=[
            SandboxStage(
                title="文化桥 ① 识别游客文化背景与搭桥机会",
                objective="先摸清游客所属国家/文化背景，从家庭、节庆、饮食、价值观等「共同点」维度寻找可搭桥的话题，而不是一上来讲差异。",
                guide_hint="开场寒暄与闲聊时先了解游客来自哪里、家庭与出行背景；从文化桥知识库调取该国对应条目（家庭聚会/节庆/饮食/敬老/勤奋等），锁定一个对方会有共鸣的共同点作为搭桥切入点。",
                kb_keywords=[
                    "中美：家庭聚会与感恩节",
                    "中美：闲聊破冰话题",
                    "中美：父母对子女的期望",
                    "中日：孝道与敬老",
                    "中日：家庭观念对比",
                    "中德：家庭观念对比",
                    "中德：子女教育期望",
                ],
                min_turns=2,
            ),
            SandboxStage(
                title="文化桥 ② 讲解中嵌入中×文化对照",
                objective="在讲解或用餐等场景中，用游客熟悉的母国锚点（节庆、饮食、器物、历史故事）对照解释中国事物，让对方一听就懂、产生亲切感。",
                guide_hint="讲中国节日时对照对方感恩节/圣诞/正月等家庭团聚传统；讲饮食时对照年夜饭/茶/筷子/酒文化；讲器物工艺时对照对方熟悉的制造或匠人传统，多用「就像你们那边的……」句式。",
                kb_keywords=[
                    "中美：感恩节聚餐与年夜饭",
                    "中美：圣诞与春节的家庭团聚",
                    "中美：节日大餐传统",
                    "中美：咖啡与茶的日常",
                    "中日：茶道与茶文化",
                    "中日：筷子饮食文化",
                    "中日：年夜饭与御节料理",
                    "中德：圣诞大餐与年夜饭",
                    "中德：啤酒与白酒文化",
                    "中德：德国制造与中国制造",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="文化桥 ③ 差异与敏感的化解",
                objective="当沟通风格、礼仪或宗教饮食等差异与敏感出现时，用「共同价值观+尊重」化解，不评判、不说教、不强行改变对方。",
                guide_hint="遇到直接/委婉、面子/直率、玩笑边界、饮食禁忌等敏感点，先共情确认对方立场，再找一个双方都认同的价值观（尊重、家庭、诚意）把差异讲成互补而不是对错。",
                kb_keywords=[
                    "中美：面子与直率的差异",
                    "中美：直接与委婉沟通",
                    "中美：幽默与玩笑边界",
                    "中美：尊重与平等观念",
                    "中日：面子与委婉",
                    "中日：间接表达",
                    "中日：礼仪与客套",
                    "中德：直接与含蓄",
                    "中德：批评与反馈方式",
                    "中德：规则与灵活",
                ],
                min_turns=3,
            ),
            SandboxStage(
                title="文化桥 ④ 情感连接与体验落地",
                objective="把文化桥落到一个具体可感的体验或心意上（一顿家常饭、一次节庆体验、一句家乡话），让游客产生被理解与被照顾的归属感。",
                guide_hint="选一个与游客文化相通的体验做「落地」：共同节庆的一顿饭、一杯茶/咖啡的闲聊、一句对方语言里的家常问候；表达时落到对方的具体情况，避免泛泛而谈。",
                kb_keywords=[
                    "中美：待客之道对比",
                    "中美：节庆饮食文化",
                    "中美：聚会文化",
                    "中日：おもてなし与热情",
                    "中日：待客之道",
                    "中日：中华料理在日本的演变",
                    "中德：待客方式对比",
                    "中德：中餐馆在德国",
                    "中德：可靠与承诺",
                ],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("互动引导", 1.2), ("表达能力", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="Emma", nationality="美国", age="33",
                personality="热情健谈，喜欢被当自己人对待",
                preferences="喜欢美食与家庭式体验，爱拍照分享",
                quirks="聊天爱用俚语，开玩笑没边界感",
                hidden="离家旅行很想家，若有人讲到和她家乡相通的地方会非常感动并愿意给高分",
            ),
            CustomerProfile(
                name="Yuki", nationality="日本", age="40",
                personality="含蓄礼貌，重视礼仪与分寸",
                preferences="喜欢茶、器物与安静的文化体验",
                quirks="有意见不明说，会委婉试探",
                hidden="很在意是否被尊重地对待，反感导游一味讲中日差异或说教，遇到共同点话题会放下防备",
            ),
            CustomerProfile(
                name="Felix", nationality="德国", age="46",
                personality="理性直接，尊重规则与专业",
                preferences="喜欢工业、工程与精密工艺话题",
                quirks="爱深究细节，喜欢就事论事",
                hidden="对导游讲解的准确性要求高，若能讲到中德在制造与工匠精神上的相通会由衷认同并主动加微信",
            ),
        ],
    ),
    # ── 情景模拟 · 应急处置与服务 ──
    SandboxTemplate(
        template_id="t_guzhen_violation",
        mode="scenario",
        title="江南古镇 · 游客违规",
        location="游客服务中心",
        task="制止游客违反景区规定（吸烟/踩踏古建），同时维护游客情绪与服务态度",
        difficulty=2,
        category="应急处置",
        opening="烟雨蒙蒙的清晨，你带团的江南古镇迎来了外国游客。团队刚进景区，你身边这位游客跨进了护栏踩踏古建筑基座，还点起了一根烟。",
        situation="你刚跨进护栏踩踏古建筑基座，还点起了一根烟——你不太清楚这里的规矩，导游会来和你沟通这件事。",
        stages=[
            SandboxStage(
                title="开场 · 上前处理",
                objective="礼貌地上前制止违规行为，说明规定与原因，不让场面僵化",
                guide_hint="先语气温和地制止，说明保护古建筑的意义，再主动提供替代方案（如指定吸烟区、讲解拍照点）",
                kb_keywords=["景区管理", "文明旅游", "服务规范"],
                min_turns=1,
            ),
            SandboxStage(
                title="应对 · 情绪与质疑",
                objective="应对游客不悦与质疑，讲清规则的同时保住服务态度",
                guide_hint="承认其想法、共情情绪，再把规则讲清楚；避免高高在上地说教",
                kb_keywords=["导游服务规范", "沟通技巧", "突发事件处理"],
                min_turns=2,
            ),
            SandboxStage(
                title="挽回 · 转危为机",
                objective="把不愉快转化为游览体验亮点，让游客继续愉快游览",
                guide_hint="顺势讲解古建筑故事，安排更好的观景位，转移注意力",
                kb_keywords=["讲解技巧", "游客心理", "情绪管理"],
                min_turns=1,
            ),
        ],
        goals=[("控场能力", 1.2), ("服务意识", 1.2), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="汉斯", nationality="德国", age="45", personality="严谨固执，讲原则但好面子",
                preferences="喜欢历史，尤其古建筑工艺", quirks="习惯直说，不高兴会当场质问",
                hidden="其实很尊重古建筑，只是因为不懂规则被当众指出而觉得丢面子，需要台阶下",
            ),
            CustomerProfile(
                name="玛丽", nationality="法国", age="52", personality="优雅但敏感，注重被尊重的感觉",
                preferences="爱拍照，对审美要求高", quirks="说话委婉但话里有话，爱用反问",
                hidden="担心错过最佳拍照时机，希望有人替她安排游览节奏",
            ),
            CustomerProfile(
                name="阿伦", nationality="美国", age="30", personality="随意外向，自我主张强",
                preferences="喜欢自由，不喜约束", quirks="爱开玩笑但容易过火",
                hidden="想找地方抽烟放松，并非故意破坏，需要被温和引导",
            ),
            CustomerProfile(
                name="佐藤", nationality="日本", age="60", personality="谦和礼貌，但非常守规矩",
                preferences="对文物和园林兴趣浓厚", quirks="发现别人违规会不安，会小声提醒",
                hidden="看重整团形象，担心自己的团队被其他游客看低",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_restaurant_etiquette",
        mode="scenario",
        title="法式餐厅 · 用餐礼仪",
        location="预订的法式西餐厅",
        task="带团在法式餐厅用餐，处理好就座、点餐、敬酒等跨文化礼仪与突发状况",
        difficulty=1,
        category="文化礼仪",
        opening="你带着一位国际游客走进预订的法式西餐厅。服务生引导入座时，这位游客对座次安排有些不满；菜单全是法语，他有些焦虑。",
        situation="你对座次安排不满（觉得被冷落），正和服务生较劲；菜单全是法语，你有点焦虑，需要导游帮忙。",
        stages=[
            SandboxStage(
                title="入座 · 化解争执",
                objective="合理安排座次、化解争执，让入座顺利",
                guide_hint="按年龄/主宾安排座次，先安抚再协调，用幽默化解尴尬",
                kb_keywords=["西餐礼仪", "座次安排", "服务规范"],
                min_turns=1,
            ),
            SandboxStage(
                title="点餐 · 跨语言沟通",
                objective="帮助不熟悉法语的游客完成点餐，讲解菜品与禁忌",
                guide_hint="主动翻译菜单、推荐招牌菜，提示饮食禁忌（如清真、素食、过敏）",
                kb_keywords=["西餐礼仪", "跨文化交流", "菜单翻译"],
                min_turns=2,
            ),
            SandboxStage(
                title="敬酒 · 分寸拿捏",
                objective="把握敬酒分寸，讲解中餐敬酒文化，避免误会",
                guide_hint="尊重不同文化对酒的态度，讲清中餐敬酒礼仪的同时不强劝酒",
                kb_keywords=["敬酒礼仪", "跨文化沟通", "餐桌文化"],
                min_turns=1,
            ),
        ],
        goals=[("文化知识", 1.3), ("服务意识", 1.1), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="艾米莉", nationality="英国", age="38", personality="得体、克制，注重分寸",
                preferences="喜欢红酒与安静的环境", quirks="对座次很敏感，讲究女士优先",
                hidden="担心被安排到不好的位置，希望被特别关照到细节",
            ),
            CustomerProfile(
                name="陈先生", nationality="新加坡", age="55", personality="讲究规矩，重视请客礼仪",
                preferences="熟悉中餐也懂西餐", quirks="爱张罗，替全团做主",
                hidden="想通过这次聚餐展现自己的待客之道，怕西餐礼仪露怯",
            ),
            CustomerProfile(
                name="露西", nationality="澳大利亚", age="27", personality="活泼不拘小节",
                preferences="喜欢尝试新奇菜品，忌麸质", quirks="说话大声，容易忽视环境",
                hidden="有麸质过敏但不爱声张，怕被特殊对待",
            ),
            CustomerProfile(
                name="法比安", nationality="法国", age="49", personality="挑剔讲究，热爱美食",
                preferences="对正宗法餐有很高期待", quirks="看到不地道的做法会皱眉头",
                hidden="把这次用餐当成检验中国导游专业度的考试",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_airport_delay",
        mode="scenario",
        title="机场接机 · 突发延误",
        location="浦东机场接机口",
        task="航班延误，团队情绪焦躁，做好解释安抚与后续行程调整安排",
        difficulty=2,
        category="接待服务",
        opening="你举着接机牌在浦东机场等待。原定 10:30 落地的航班通知延误 3 小时，多位游客已在群里抱怨，几位上了年纪的游客明显疲惫焦虑。",
        stages=[
            SandboxStage(
                title="第一时间 · 说明安抚",
                objective="主动告知延误、表达关心，稳住团队情绪",
                guide_hint="第一时间公开透明说明情况，表达抱歉与关心，别让游客从别人口中听说",
                kb_keywords=["接机服务", "航班延误", "安抚技巧"],
                min_turns=1,
            ),
            SandboxStage(
                title="安顿 · 解决当下",
                objective="为旅客提供休息、饮水等实际帮助，协调改签/餐食",
                guide_hint="协调休息区、提供餐食，主动联系航司确认改签，让游客感到被安排",
                kb_keywords=["机场服务", "突发事件处理", "行程调整"],
                min_turns=2,
            ),
            SandboxStage(
                title="后续 · 行程衔接",
                objective="衔接后续行程安排，消除游客对行程被耽误的担忧",
                guide_hint="给出明确的行程补救方案（压缩项目/加场），承诺跟进到底",
                kb_keywords=["行程安排", "应变能力", "承诺管理"],
                min_turns=1,
            ),
        ],
        goals=[("控场能力", 1.2), ("服务意识", 1.3), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="张女士", nationality="中国", age="58", personality="急性子，爱抱怨但讲理",
                preferences="怕耽误女儿假期安排", quirks="喜欢找旅行社负责人理论",
                hidden="最担心后面行程缩水，需要明确承诺才安心",
            ),
            CustomerProfile(
                name="大卫", nationality="加拿大", age="41", personality="冷静理性，就事论事",
                preferences="讲究效率与信息透明", quirks="会不断追问具体时间点",
                hidden="需要精确的航班动态和备选方案才愿意放心",
            ),
            CustomerProfile(
                name="李姐", nationality="中国", age="65", personality="随和但有轻微心脏问题",
                preferences="怕累怕等", quirks="不会主动提要求，只是沉默焦虑",
                hidden="身体不适需要被主动关照，不好意思开口",
            ),
            CustomerProfile(
                name="安娜", nationality="西班牙", age="33", personality="热情外向，容易受情绪影响",
                preferences="喜欢拍照打卡", quirks="会用社交媒体直播行程",
                hidden="担心行程泡汤影响自己的旅行记录，需要亮点补偿",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_temple_taboo",
        mode="scenario",
        title="古寺参观 · 宗教禁忌",
        location="千年古寺",
        task="带领团队参观古寺，引导文明礼佛、避免宗教禁忌，并处理一次无意冒犯",
        difficulty=3,
        category="文化礼仪",
        opening="你带队走进千年古寺。青烟缭绕中，你身边这位游客正对着佛像举起手机准备拍摄，还和同伴大声说笑。一位僧人看向这边。",
        situation="你正对着佛像举起手机准备拍照，还和同伴大声说笑——你不清楚这里的禁忌，僧人已经看向这边，导游需要引导你注意礼仪。",
        stages=[
            SandboxStage(
                title="引导 · 文明参观",
                objective="以尊重的方式说明寺庙礼仪与禁忌，防止冒犯",
                guide_hint="先温和说明「殿内请勿拍摄」「请保持安静」，解释佛教礼仪背后的文化含义",
                kb_keywords=["宗教禁忌", "佛教礼仪", "文明旅游"],
                min_turns=1,
            ),
            SandboxStage(
                title="处理 · 无意冒犯",
                objective="在游客已造成冒犯时妥善处理，维护与寺方的良好关系",
                guide_hint="主动向寺方致歉说明，为游客讲解规矩背后的慈悲心，化误会为理解",
                kb_keywords=["宗教文化", "跨文化交流", "服务补救"],
                min_turns=2,
            ),
            SandboxStage(
                title="深化 · 传递文化",
                objective="把宗教禁忌讲成有温度的文化故事，让游客敬畏并记住",
                guide_hint="结合历史典故与建筑艺术讲解，让游客带着尊重与兴趣离开",
                kb_keywords=["佛教艺术", "寺庙建筑", "讲解技巧"],
                min_turns=1,
            ),
        ],
        goals=[("文化知识", 1.4), ("控场能力", 1.1), ("服务意识", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="保罗", nationality="意大利", age="48", personality="热忱好奇，但随性",
                preferences="痴迷艺术与古建筑，随身带相机", quirks="看到喜欢的就想拍，忽略场合",
                hidden="并非不敬，而是太热爱艺术想记录，需要被引导「什么时候可以拍」",
            ),
            CustomerProfile(
                name="樱花子", nationality="日本", age="70", personality="虔诚安静，熟悉佛教",
                preferences="常去寺庙", quirks="看到他人冒犯会皱眉但没有话语权",
                hidden="在意同行游客的态度是否会影响整团名声",
            ),
            CustomerProfile(
                name="杰克", nationality="英国", age="35", personality="理性怀疑，不太信宗教",
                preferences="喜欢历史实证", quirks="喜欢追问「为什么要这样」",
                hidden="想搞懂宗教规矩的逻辑，讲通了反而更配合",
            ),
            CustomerProfile(
                name="阿依古丽", nationality="土耳其", age="40", personality="温和有礼，信仰伊斯兰教",
                preferences="对宗教礼仪有天然敏感", quirks="会留心同行的尊重程度",
                hidden="希望导游对所有宗教信仰一视同仁地尊重",
            ),
        ],
    ),
    # ── 即兴讲解 ──
    SandboxTemplate(
        template_id="t_yungang",
        mode="narrate",
        title="云冈石窟 · 第20窟",
        location="云冈石窟第20窟前",
        task="向游客即兴讲解露天大佛的开凿背景、艺术特色与历史价值，并应答提问",
        difficulty=2,
        category="遗产讲解",
        opening="你带团停在云冈石窟第20窟的露天大佛前。阳光洒在巨佛身上，游客们仰头惊叹。一位法国老游客推了推眼镜，认真地等着你开口。",
        stages=[
            SandboxStage(
                title="开场 · 引客入胜",
                objective="用有吸引力的开场点出大佛地位，激发兴趣",
                guide_hint="用「世界文化遗产」「露天巨佛」等关键词开场，先立住讲解气势",
                kb_keywords=["云冈石窟", "世界文化遗产", "开场讲解"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 历史与艺术",
                objective="讲清开凿年代、昙曜背景与犍陀罗艺术风格",
                guide_hint="讲北魏开凿背景、昙曜五窟、希腊-印度犍陀罗风格对佛像造型的影响",
                kb_keywords=["云冈石窟", "昙曜五窟", "犍陀罗艺术", "北魏"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 追问互动",
                objective="回应游客的细节追问，把讲解引向文化价值",
                guide_hint="对风化、露天成因等问题给出现实回应，再升华到文明交流的价值",
                kb_keywords=["文物保护", "文明交流", "佛教艺术"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("沟通表达", 1.2), ("互动引导", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="马塞尔", nationality="法国", age="55", personality="博学好奇，艺术眼光高",
                preferences="研究东西方艺术交流", quirks="会引用欧洲艺术史来类比",
                hidden="期待听到大佛与西方艺术的关联，若没讲到会觉得讲解单薄",
            ),
            CustomerProfile(
                name="琳达", nationality="美国", age="28", personality="活泼爱提问，知识面一般",
                preferences="喜欢故事性讲解", quirks="会打断提问，问题天马行空",
                hidden="希望讲解有故事、有画面感，纯年代数字她会走神",
            ),
            CustomerProfile(
                name="周老师", nationality="中国", age="62", personality="博学严谨，有备而来",
                preferences="熟读佛教史", quirks="会温和地追问细节印证你的水平",
                hidden="心里在默默检验你的讲解是否准确严谨",
            ),
            CustomerProfile(
                name="卡尔", nationality="德国", age="38", personality="理性好奇，喜欢数据",
                preferences="关注保护与风化问题", quirks="爱问「为什么」「多久以后」",
                hidden="关心文物保护的现状与困境，愿意听深度内容",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_guzhen_narrate",
        mode="narrate",
        title="江南古镇 · 水乡格局",
        location="江南古镇河街",
        task="向游客介绍「小桥流水人家」的水乡格局、建筑特色与商贸人文，并即兴应答",
        difficulty=1,
        category="风貌讲解",
        opening="摇橹船轻轻靠岸，你们走上青石板路。河两岸白墙黛瓦、廊棚绵延，一阵桂花香混着叫卖声飘来。游客们举着手机，等你的第一句话。",
        stages=[
            SandboxStage(
                title="开场 · 格局引入",
                objective="用生动语言点出水乡格局，让游客建立空间画面",
                guide_hint="从「水-桥-街-宅」的肌理讲起，讲清为什么是「小桥流水人家」",
                kb_keywords=["江南古镇", "水乡格局", "小桥流水"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲建筑 · 马头墙与廊棚",
                objective="讲清马头墙、廊棚等建筑特色及其功能智慧",
                guide_hint="从防火、遮阳避雨的功能切入，讲建筑里的生活智慧",
                kb_keywords=["马头墙", "廊棚", "江南民居"],
                min_turns=2,
            ),
            SandboxStage(
                title="讲人文 · 商贸与故事",
                objective="把古镇的商贸历史与人间烟火讲成故事",
                guide_hint="结合漕运/丝绸/小吃等讲商贸，用一个人物或场景让游客共情",
                kb_keywords=["古镇商贸", "江南人文", "漕运"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.3), ("互动引导", 1.2), ("沟通表达", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="苏珊", nationality="美国", age="47", personality="感性浪漫，爱拍照",
                preferences="喜欢有画面感的描述", quirks="经常被路边小店吸引走神",
                hidden="希望讲解能配合她的拍照节奏，给她留出记录美好的时间",
            ),
            CustomerProfile(
                name="黄先生", nationality="中国台湾", age="50", personality="怀旧温和",
                preferences="对江南水乡有乡愁", quirks="会主动分享自己对老建筑的理解",
                hidden="期待听到古镇原住民的生活细节，而非只讲游客打卡点",
            ),
            CustomerProfile(
                name="伊莎贝拉", nationality="西班牙", age="34", personality="热情话多",
                preferences="喜欢听故事和本地八卦", quirks="爱接话、爱开玩笑",
                hidden="想了解古镇的市井生活与美食，好发到自己的旅行账号",
            ),
            CustomerProfile(
                name="诺亚", nationality="英国", age="29", personality="安静认真，爱做笔记",
                preferences="关注建筑细节与功能", quirks="会掏出小本子记录",
                hidden="希望听到专业的建筑知识，能被当成懂行的游客对待",
            ),
        ],
    ),
    # ── 路线带团（多站点长场景） ──
    # ══════════════ 以下为新增 18 个场景 ══════════════
    # ── 情景模拟 · 应急处置 ──
    SandboxTemplate(
        template_id="t_hotel_fire",
        mode="scenario",
        title="酒店火警 · 疏散逃生",
        location="酒店客房走廊",
        task="深夜酒店火警骤响，游客惊慌失措，引导其冷静疏散、清点人数并妥善安置",
        difficulty=3,
        category="应急处置",
        opening="凌晨一点，酒店火警铃声骤然响起，走廊里弥漫着烟味。你拍门叫醒团队游客，你面前这位游客只穿着睡衣、光着脚，脸色煞白地站在门口，楼道里已有人慌乱奔跑。",
        situation="你被火警惊醒后慌得六神无主，只穿了睡衣就跑出来，手机和贵重物品都落在房间里，你担心得腿发软，不知道该怎么办。",
        stages=[
            SandboxStage(
                title="应急 · 冷静引导",
                objective="第一时间安抚游客情绪，明确疏散路线与安全要求，避免慌乱",
                guide_hint="用坚定的语气让游客冷静，提示湿毛巾捂口鼻、弯腰低姿、走安全楼梯不乘电梯",
                kb_keywords=["火灾疏散", "安全逃生", "应急预案"],
                min_turns=1,
            ),
            SandboxStage(
                title="疏散 · 清点与确认",
                objective="引导游客完成疏散，清点人数，确认无滞留人员",
                guide_hint="组织游客沿安全通道有序撤离，到集合点逐一清点，询问是否有人折返取物",
                kb_keywords=["清点人数", "疏散路线", "导游职责"],
                min_turns=2,
            ),
            SandboxStage(
                title="安置 · 后续处理",
                objective="疏散后安抚游客、协调临时安置，配合酒店查明情况",
                guide_hint="为受惊游客安排休息与保暖，配合酒店/消防说明情况，跟进物品取回与理赔",
                kb_keywords=["游客安抚", "酒店协调", "突发事件处理"],
                min_turns=1,
            ),
        ],
        goals=[("控场能力", 1.4), ("服务意识", 1.2), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="王小姐", nationality="中国", age="27", personality="独立但易慌张",
                preferences="习惯熬夜刷手机", quirks="遇事会反复打电话给家人",
                hidden="手机和钱包落在房间里，最怕贵重物品丢失，需要导游帮她确认",
            ),
            CustomerProfile(
                name="汉克", nationality="美国", age="45", personality="冷静强势，主意多",
                preferences="讲究效率", quirks="会质疑导游的疏散安排并想自己行动",
                hidden="其实也紧张，但更怕显得软弱，需要被认可判断力",
            ),
            CustomerProfile(
                name="赵奶奶", nationality="中国", age="68", personality="行动慢，腿脚不便",
                preferences="睡眠浅", quirks="紧张时会抓导游胳膊不放",
                hidden="有心脏病史，怕走楼梯太急，需要被专人搀扶照顾",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_guest_illness",
        mode="scenario",
        title="游客突发 · 疾病处置",
        location="旅游大巴上",
        task="游客在行程中突发身体不适，正确判断、及时送医并做好全团安排",
        difficulty=3,
        category="应急处置",
        opening="大巴正驶往下一个景点，你身边这位游客突然面色发白、捂住胸口说喘不上气。车上其他人开始探头张望，有人小声议论。",
        situation="你突然胸闷气短、头晕冒汗，怀疑是旧疾发作，又怕耽误全团行程不敢声张，只能小声向导游求助。",
        stages=[
            SandboxStage(
                title="判断 · 初步处置",
                objective="迅速询问症状、判断轻重，采取正确的初步急救措施",
                guide_hint="让患者平卧/半卧、解开衣领、询问病史与药物，切勿随意喂药或搬动",
                kb_keywords=["急救常识", "疾病判断", "游客健康"],
                min_turns=1,
            ),
            SandboxStage(
                title="送医 · 协调安排",
                objective="决定送医并妥善安排，协调车辆、医院与全团行程",
                guide_hint="情况紧急立即拨打120或就近送医，安排陪护；与旅行社汇报并调整全团行程",
                kb_keywords=["紧急送医", "行程调整", "应急预案"],
                min_turns=2,
            ),
            SandboxStage(
                title="关怀 · 后续跟进",
                objective="跟进患者情况，安抚患者与全团情绪，做好善后",
                guide_hint="就医后主动探视/电话跟进，告知其他游客情况稳定，协调费用与保险事宜",
                kb_keywords=["游客关怀", "医疗费用", "旅游保险"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("控场能力", 1.3), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="陈叔叔", nationality="中国", age="63", personality="要强，不愿麻烦别人",
                preferences="有高血压史", quirks="难受也说「没事，歇歇就好」",
                hidden="怕导游觉得他事多，但确实胸口发闷，需要被坚持送医",
            ),
            CustomerProfile(
                name="米娅", nationality="德国", age="29", personality="谨慎细致，注重健康",
                preferences="随身带常用药", quirks="会查阅症状描述",
                hidden="担心导游处置不当，希望听到专业判断与明确的就医安排",
            ),
            CustomerProfile(
                name="老刘", nationality="中国", age="58", personality="热心爱张罗",
                preferences="喜欢管全团的事", quirks="会替病人做主",
                hidden="怕耽误自己后面的行程，希望导游尽快给出全团安排",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_lost_passport",
        mode="scenario",
        title="护照遗失 · 补办协助",
        location="酒店大堂",
        task="游客护照遗失，安抚情绪、协助报案挂失并协调补办证件手续",
        difficulty=3,
        category="应急处置",
        opening="出发去机场前一小时，你面前这位游客在酒店大堂翻遍了背包，脸色越来越难看——护照不见了。他明天就要离境，声音已经开始发抖。",
        situation="你的护照在酒店丢了，明天就要离境，你越想越慌，脑子里一片空白，只记得最后一次见到护照是在昨晚的房间里。",
        stages=[
            SandboxStage(
                title="安抚 · 梳理线索",
                objective="稳住游客情绪，帮其回忆护照最后出现的位置与时间",
                guide_hint="先安抚「一定找得到」，带其回房间和沿途仔细回忆查找，别急着下结论",
                kb_keywords=["护照遗失", "游客安抚", "应急处置"],
                min_turns=1,
            ),
            SandboxStage(
                title="挂失 · 报案流程",
                objective="确认遗失后指导报案挂失，开具遗失证明",
                guide_hint="告知携带护照复印件/照片到当地公安机关出入境管理部门报案挂失，取得报失证明",
                kb_keywords=["挂失报案", "出入境管理", "证件办理"],
                min_turns=2,
            ),
            SandboxStage(
                title="补办 · 协调离境",
                objective="协助补办旅行证件，协调改签机票与后续行程",
                guide_hint="外国游客需联系使领馆申请旅行证；同步改签航班、调整行程，向旅行社报备",
                kb_keywords=["旅行证", "使领馆", "行程改签"],
                min_turns=2,
            ),
        ],
        goals=[("控场能力", 1.2), ("服务意识", 1.3), ("文化知识", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="奥利弗", nationality="英国", age="34", personality="表面镇定，内心焦虑",
                preferences="做事有条理", quirks="会反复翻包确认，语速变快",
                hidden="担心护照丢失会影响征信和回国安排，需要导游给出清晰步骤",
            ),
            CustomerProfile(
                name="崔太太", nationality="韩国", age="52", personality="急性子，爱自责",
                preferences="习惯把证件放夹层", quirks="一边念叨「都怪我」一边翻找",
                hidden="最怕耽误回国航班损失机票钱，希望导游帮她向航司争取",
            ),
            CustomerProfile(
                name="汤姆", nationality="澳大利亚", age="41", personality="乐观但粗心",
                preferences="丢三落四", quirks="会开玩笑缓解紧张",
                hidden="其实很慌，需要导游给确定的方案，玩笑只是掩饰",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_baggage_loss",
        mode="scenario",
        title="行李丢失 · 查找理赔",
        location="到达机场行李转盘",
        task="游客托运行李未随航班到达，安抚情绪、协助报失查找并衔接行程",
        difficulty=2,
        category="应急处置",
        opening="行李转盘已经空转了三圈，游客们的箱子陆续取走，你面前这位游客的行李箱始终没出现。他攥着行李票，眉头越皱越紧。",
        situation="你转机时托运的行李箱没到，里面装着你所有换洗衣物和给家人带的礼物，你担心行李被弄丢，也怕耽误接下来的行程。",
        stages=[
            SandboxStage(
                title="报失 · 及时登记",
                objective="第一时间带游客到行李查询处报失登记，留下联系方式与行程信息",
                guide_hint="凭行李票（行李牌）到航空公司行李查询处填写丢失登记，索要受理编号与联系方式",
                kb_keywords=["行李报失", "行李票", "航空服务"],
                min_turns=1,
            ),
            SandboxStage(
                title="衔接 · 安排行程",
                objective="帮助游客解决燃眉之急（换洗衣物/洗漱用品），不耽误后续行程",
                guide_hint="协调航司提供临时生活用品或先行垫付，告知后续航班送达安排，继续正常行程",
                kb_keywords=["行李理赔", "临时用品", "行程衔接"],
                min_turns=2,
            ),
            SandboxStage(
                title="跟进 · 理赔协调",
                objective="跟进行李查找进度，指导游客按规索赔",
                guide_hint="按规定时限查找，超期按国际公约/民航规定申请赔偿，保留票据证据",
                kb_keywords=["行李赔偿", "民航规定", "游客权益"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("控场能力", 1.1), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="小周", nationality="中国", age="26", personality="年轻急躁，看重个人物品",
                preferences="出门爱带全套化妆品", quirks="会反复追问「到底多久能找到」",
                hidden="箱子里的礼物是给家人的，怕行程结束前拿不到",
            ),
            CustomerProfile(
                name="莉娜", nationality="瑞典", age="39", personality="冷静条理",
                preferences="习惯提前规划", quirks="会记录每个处理环节的时间",
                hidden="担心航司拖延，希望导游推动航司给出明确答复时限",
            ),
            CustomerProfile(
                name="保罗·王", nationality="美国", age="57", personality="讲究权益",
                preferences="熟悉消费者权益", quirks="张口就提「我要投诉索赔」",
                hidden="想借机多要赔偿，但也希望行程不受影响",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_weather_typhoon",
        mode="scenario",
        title="台风预警 · 行程改期",
        location="景区检票口",
        task="台风预警导致行程取消，安抚游客、说明原因并协调改期或替代方案",
        difficulty=2,
        category="应急处置",
        opening="你们刚到景区门口，官方通知因台风预警景区今日关闭。天边乌云压顶，你面前这位游客手里攥着门票，一脸难以置信。",
        situation="你起了大早专门来这个景区，到了门口却被告知因台风关闭，你既失望又生气，觉得白跑一趟，想找人讨个说法。",
        stages=[
            SandboxStage(
                title="说明 · 透明告知",
                objective="第一时间向游客说明关闭原因与安全考量，争取理解",
                guide_hint="以安全为由说明台风风险，出示官方通知，强调「安全第一」而非景区失职",
                kb_keywords=["台风预警", "安全第一", "行程变更"],
                min_turns=1,
            ),
            SandboxStage(
                title="补救 · 替代方案",
                objective="为游客安排替代景点或改期方案，减少行程损失",
                guide_hint="提出室内替代景点/改期重游/退票处理等选项，尊重游客选择",
                kb_keywords=["替代方案", "行程调整", "退票改期"],
                min_turns=2,
            ),
            SandboxStage(
                title="安抚 · 情绪管理",
                objective="化解游客失望情绪，把遗憾转化为期待",
                guide_hint="共情游客期待落空的心情，用改期后的亮点做钩子，承诺优先保障",
                kb_keywords=["游客心理", "情绪安抚", "服务补救"],
                min_turns=1,
            ),
        ],
        goals=[("沟通表达", 1.2), ("服务意识", 1.2), ("控场能力", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="小林", nationality="中国", age="31", personality="爱做攻略，追求打卡",
                preferences="提前一个月规划行程", quirks="会翻出天气预报反驳",
                hidden="这次旅行是特意请年假来的，怕错过就再也没有机会",
            ),
            CustomerProfile(
                name="莫妮卡", nationality="意大利", age="48", personality="浪漫感性，重体验",
                preferences="喜欢摄影与自然", quirks="会感叹「旅行要随缘」",
                hidden="其实很失望，但愿意接受合理替代，需要被安抚到位",
            ),
            CustomerProfile(
                name="高先生", nationality="中国", age="60", personality="较真，认死理",
                preferences="讲究性价比", quirks="反复问「那门票钱怎么算」",
                hidden="担心改期后行程冲突，需要明确的时间安排承诺",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_traffic_jam",
        mode="scenario",
        title="堵车迟到 · 行程压缩",
        location="高速路上的旅游大巴",
        task="遇大堵车导致景点行程紧张，向游客说明并灵活压缩安排，稳住民怨",
        difficulty=2,
        category="应急处置",
        opening="高速路上车流一眼望不到头，导航显示预计还要堵两个小时。原定下午的博物馆预约眼看就要错过，车上有人开始叹气抱怨。",
        situation="你们被堵在高速上，眼看博物馆预约时间要过了，你越想越急，担心行程被砍，开始怀疑是不是路线安排出了问题。",
        stages=[
            SandboxStage(
                title="告知 · 管理预期",
                objective="坦诚说明堵车情况与预计延误，先安抚再给方案",
                guide_hint="及时告知现状与预计到达时间，承认客观原因，给游客「被尊重」的感觉",
                kb_keywords=["堵车延误", "预期管理", "沟通技巧"],
                min_turns=1,
            ),
            SandboxStage(
                title="调整 · 灵活安排",
                objective="联系景点协调预约/推迟，灵活压缩或重排当日行程",
                guide_hint="电话协调博物馆保留名额，调整景点先后顺序，保证核心项目不丢",
                kb_keywords=["预约协调", "行程压缩", "应变能力"],
                min_turns=2,
            ),
            SandboxStage(
                title="补救 · 弥补体验",
                objective="用加餐、加亮点等方式弥补延误损失，平息不满",
                guide_hint="途中安排特色餐/车内讲解活跃气氛，到达后优先安排重点，给游客「赚到了」的感觉",
                kb_keywords=["服务补救", "游客情绪", "体验设计"],
                min_turns=1,
            ),
        ],
        goals=[("控场能力", 1.3), ("沟通表达", 1.1), ("服务意识", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="陆先生", nationality="中国", age="42", personality="事业型，时间观念强",
                preferences="讲究效率", quirks="会盯着手机看时间",
                hidden="下午有重要电话会议，怕行程拖到晚上耽误正事",
            ),
            CustomerProfile(
                name="玛蒂尔达", nationality="法国", age="33", personality="优雅挑剔",
                preferences="重视体验质量", quirks="会小声评价行程安排",
                hidden="最怕走马观花式压缩，宁缺毋滥，希望保留核心景点的完整时间",
            ),
            CustomerProfile(
                name="阿芳", nationality="中国", age="28", personality="活泼爱玩",
                preferences="喜欢拍照打卡", quirks="会在群里实时直播进度",
                hidden="担心错过预约的网红博物馆，需要被承诺保底方案",
            ),
        ],
    ),
    # ── 情景模拟 · 服务规范 ──
    SandboxTemplate(
        template_id="t_shopping_refund",
        mode="scenario",
        title="购物纠纷 · 退货处理",
        location="景区购物店门口",
        task="游客购物后想退货与店家发生纠纷，维护游客权益并妥善协调处理",
        difficulty=2,
        category="服务规范",
        opening="一位游客刚在景区购物店买了一块玉石，出门就嚷着要退货。店员黑着脸说「离柜概不退换」，双方在门口越吵越大声，周围游客纷纷侧目。",
        situation="你刚在店里花高价买了块玉石，出门后发现价格虚高且成色存疑，你回去要求退货，店员却一口回绝，你现在又气又后悔。",
        stages=[
            SandboxStage(
                title="倾听 · 了解诉求",
                objective="先倾听游客诉求与店方说法，稳住场面避免冲突升级",
                guide_hint="把双方分开沟通，先听游客说清楚购买过程与退货理由，再核实店方政策",
                kb_keywords=["购物纠纷", "倾听沟通", "游客权益"],
                min_turns=1,
            ),
            SandboxStage(
                title="调解 · 依法协调",
                objective="依据旅游法/消费者权益保护法协调退货退款，维护游客合法权益",
                guide_hint="提示「旅游购物30天无理由退货」等政策，帮助游客与店家/旅行社协调",
                kb_keywords=["退货政策", "消费者权益", "旅游法"],
                min_turns=2,
            ),
            SandboxStage(
                title="引导 · 理性消费",
                objective="借机引导游客理性消费，避免再次被诱导购物",
                guide_hint="提醒购物风险、索要票据，介绍正规购物渠道与维权途径",
                kb_keywords=["理性消费", "防购物陷阱", "维权途径"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("控场能力", 1.2), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="孙姐", nationality="中国", age="46", personality="精明泼辣，不吃亏",
                preferences="喜欢砍价购物", quirks="嗓门大，爱当众讲道理",
                hidden="其实最怕买到假货，希望导游帮她分辨真假并做主退货",
            ),
            CustomerProfile(
                name="珍妮", nationality="加拿大", age="35", personality="礼貌但坚定",
                preferences="注重消费者权益", quirks="会用手机查政策条文",
                hidden="想确认退货是否符合法律，不希望被当冤大头",
            ),
            CustomerProfile(
                name="吴伯", nationality="中国", age="64", personality="耳根软，易被说服",
                preferences="爱给家人带礼物", quirks="被店员一说就犹豫",
                hidden="怕退货不成还丢面子，希望导游给个台阶和明确说法",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_food_allergy",
        mode="scenario",
        title="饮食过敏 · 禁忌确认",
        location="团队餐厅",
        task="游客有食物过敏/禁忌，点餐前主动确认、协调厨房避开过敏原，防患未然",
        difficulty=2,
        category="服务规范",
        opening="晚餐时间，餐厅上菜前，你面前这位游客突然拉住你，小声说自己对花生严重过敏，但菜单上很多菜看不出是否含花生。",
        situation="你有严重的花生过敏，稍不注意就会呼吸困难，可菜单上根本看不出哪些菜含花生，你怕开口被嫌弃事多，又不敢不开口。",
        stages=[
            SandboxStage(
                title="确认 · 过敏登记",
                objective="认真登记游客过敏原与严重程度，纳入用餐安排",
                guide_hint="逐项询问过敏原、忌口范围与严重程度，记录在案并告知厨房",
                kb_keywords=["食物过敏", "游客健康", "餐饮服务"],
                min_turns=1,
            ),
            SandboxStage(
                title="协调 · 厨房对接",
                objective="与餐厅协调避开过敏原，为游客安排安全餐食",
                guide_hint="亲自到厨房确认菜品用料，要求单独制作/替换菜品，杜绝交叉污染",
                kb_keywords=["过敏原规避", "餐饮协调", "服务细节"],
                min_turns=2,
            ),
            SandboxStage(
                title="应急 · 过敏预案",
                objective="掌握过敏应急处理预案，万一误食能正确应对",
                guide_hint="告知游客应急药品随身携带，掌握送医与急救流程，关键时刻立即处置",
                kb_keywords=["过敏急救", "应急预案", "游客安全"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.4), ("沟通表达", 1.0), ("控场能力", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="艾米", nationality="美国", age="24", personality="害羞怕麻烦别人",
                preferences="严格素食加花生过敏", quirks="说话小声，怕被嫌弃",
                hidden="过敏严重到会休克，但不好意思反复强调，需要导游主动担起责任",
            ),
            CustomerProfile(
                name="冯先生", nationality="中国", age="53", personality="细心爱操心",
                preferences="对饮食卫生要求高", quirks="会亲自检查餐具",
                hidden="担心餐厅不靠谱，希望看到导游实际去厨房确认而不是口头答应",
            ),
            CustomerProfile(
                name="伊莲娜", nationality="俄罗斯", age="38", personality="直接坦率",
                preferences="乳糖不耐受", quirks="点菜会直接提要求",
                hidden="希望导游对全团饮食禁忌统一管理，别只照顾个别游客",
            ),
        ],
    ),
    # ── 情景模拟 · 接待服务 ──
    SandboxTemplate(
        template_id="t_hotel_checkin",
        mode="scenario",
        title="入住问题 · 房间调换",
        location="酒店前台",
        task="游客对分配的房间不满（朝向差/噪音大/设施坏），妥善处理换房或补偿",
        difficulty=1,
        category="接待服务",
        opening="团队刚拿到房卡，你面前这位游客就气冲冲走回前台，说自己的房间临街太吵、空调还是坏的，要求立刻换房。",
        situation="你分到的房间临街，半夜肯定睡不好，空调还是坏的，你觉得导游根本没用心安排，非常不满。",
        stages=[
            SandboxStage(
                title="倾听 · 核实问题",
                objective="认真倾听游客不满，实地核实房间问题，不当场敷衍",
                guide_hint="先安抚情绪，随游客到房间查看实际情况，确认问题真实存在",
                kb_keywords=["酒店入住", "投诉处理", "服务规范"],
                min_turns=1,
            ),
            SandboxStage(
                title="协调 · 换房补偿",
                objective="与酒店协调换房或给予补偿，满足游客合理诉求",
                guide_hint="争取同楼层安静房/高层房，若无房可换则谈升级/赠餐等补偿",
                kb_keywords=["换房协调", "酒店沟通", "服务补救"],
                min_turns=2,
            ),
            SandboxStage(
                title="回访 · 确保满意",
                objective="入住后回访确认问题解决，让游客感到被重视",
                guide_hint="晚上或次晨主动询问入住体验，确认无遗留问题",
                kb_keywords=["回访关怀", "服务质量", "游客满意度"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("沟通表达", 1.1), ("控场能力", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="郭女士", nationality="中国", age="39", personality="讲究生活品质",
                preferences="睡眠浅，怕吵", quirks="会拍照留证据",
                hidden="昨天坐了一夜飞机，非常需要好好睡一觉，情绪源于疲惫",
            ),
            CustomerProfile(
                name="奥托", nationality="德国", age="50", personality="严谨较真",
                preferences="讲究合同与约定", quirks="会翻出预订确认单对照",
                hidden="觉得房间与预订不符是违约，需要导游认真对待而不是糊弄",
            ),
            CustomerProfile(
                name="小雅", nationality="中国", age="30", personality="随和但有自己的坚持",
                preferences="旅行博主，拍vlog", quirks="会直播房间实况",
                hidden="房间体验影响她的视频素材，希望住得满意好出片",
            ),
        ],
    ),
    # ── 情景模拟 · 特殊游客 ──
    SandboxTemplate(
        template_id="t_elderly_care",
        mode="scenario",
        title="老年游客 · 细致照护",
        location="景区爬坡路段",
        task="老年游客体力不支/行动不便，放慢节奏、主动关怀并安排休息",
        difficulty=2,
        category="特殊游客",
        opening="爬坡到一半，你身边这位老游客扶着栏杆喘得厉害，说头晕想歇一歇。前边年轻游客已经走出老远，他不好意思让大家等。",
        situation="你爬坡有些吃力，现在头晕腿软，又怕耽误全团时间不敢说，只能硬撑着说「没事」，其实急需坐下休息。",
        stages=[
            SandboxStage(
                title="体察 · 主动关怀",
                objective="敏锐察觉游客身体不适，主动安排休息，不让其硬撑",
                guide_hint="立刻安排坐下休息、补水，询问病史与常用药，叮嘱「安全第一」",
                kb_keywords=["老年游客", "主动关怀", "游客安全"],
                min_turns=1,
            ),
            SandboxStage(
                title="调整 · 节奏安排",
                objective="调整游览节奏与路线，兼顾游客体能与全团安排",
                guide_hint="放慢行进速度、缩短步行段，安排观光车/近路，与全团约定汇合点",
                kb_keywords=["节奏控制", "行程调整", "无障碍服务"],
                min_turns=2,
            ),
            SandboxStage(
                title="守护 · 全程照护",
                objective="全程留意游客状态，提供细致照护",
                guide_hint="专人陪伴、随身带水与药品提示、定时询问身体状况，紧急情况预案",
                kb_keywords=["贴心服务", "健康监护", "应急保障"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.4), ("控场能力", 1.1), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="周爷爷", nationality="中国", age="72", personality="要强倔强",
                preferences="年轻时是运动员", quirks="不肯承认自己体力不行",
                hidden="有冠心病史，怕被当累赘，需要导游用「安排座」「顺路歇」的方式给台阶",
            ),
            CustomerProfile(
                name="王阿姨", nationality="中国", age="61", personality="温柔体面",
                preferences="喜欢拍照留念", quirks="脚不好走路一瘸一拐",
                hidden="怕跟不上团被落下，希望导游能记得照顾她，又不好意思主动开口",
            ),
            CustomerProfile(
                name="晓彤", nationality="中国", age="38", personality="孝顺细心但容易焦虑",
                preferences="陪母亲出游，关注长辈健康", quirks="总追问「我妈这样没事吧」",
                hidden="请了年假陪母亲，怕照顾不周又不敢麻烦导游，需要被主动宽慰",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_child_family",
        mode="scenario",
        title="带娃家庭 · 亲子出行",
        location="主题乐园入口",
        task="带娃家庭出行节奏特殊，兼顾孩子兴趣与安全，处理孩子闹情绪等状况",
        difficulty=2,
        category="特殊游客",
        opening="主题乐园门口，你面前这位年轻妈妈一手拉着哭闹的孩子，一手拎着大包小包，满脸无奈。孩子非要立刻去买冰淇淋，不去就坐地上撒泼。",
        situation="你带孩子来玩，孩子又累又饿开始闹情绪，你一个人哄不过来，既怕耽误全团又怕孩子吵到别人，急得快哭出来。",
        stages=[
            SandboxStage(
                title="体察 · 优先照顾",
                objective="第一时间帮助妈妈安抚孩子，缓解窘迫，不让其孤立无援",
                guide_hint="主动上前帮忙提东西、哄孩子，协调就近买水/零食，先稳住孩子情绪",
                kb_keywords=["亲子游客", "儿童照护", "服务意识"],
                min_turns=1,
            ),
            SandboxStage(
                title="安排 · 节奏与安全",
                objective="为带娃家庭安排合适的游览节奏，强调儿童安全",
                guide_hint="推荐适合孩子的项目与休息点，提醒看护孩子、防走失，安排灵活集合时间",
                kb_keywords=["儿童安全", "行程安排", "特殊群体服务"],
                min_turns=2,
            ),
            SandboxStage(
                title="互动 · 亲子体验",
                objective="把孩子的兴趣变成行程亮点，让全家都玩得尽兴",
                guide_hint="讲解中加入孩子感兴趣的故事/互动，安排亲子拍照点，让孩子参与进来",
                kb_keywords=["互动讲解", "亲子体验", "游客满意度"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("互动引导", 1.2), ("控场能力", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="林妈妈", nationality="中国", age="32", personality="温柔但疲惫",
                preferences="独自带娃出游", quirks="一手抱娃一手看手机导航",
                hidden="睡眠不足情绪快到极限，最需要有人搭把手，而非讲道理",
            ),
            CustomerProfile(
                name="萨拉", nationality="英国", age="37", personality="注重教育体验",
                preferences="喜欢寓教于乐的安排", quirks="会追问「这个项目孩子能学到什么」",
                hidden="担心景点对孩子太无聊，希望行程兼顾孩子兴趣",
            ),
            CustomerProfile(
                name="刘爸", nationality="中国", age="40", personality="佛系随和",
                preferences="孩子说什么是什么", quirks="由着孩子乱跑，容易走散",
                hidden="其实怕孩子走丢，希望导游帮忙盯着，又拉不下脸求助",
            ),
        ],
    ),
    # ── 情景模拟 · 文化礼仪 ──
    SandboxTemplate(
        template_id="t_vegetarian_request",
        mode="scenario",
        title="素食清真 · 饮食安排",
        location="团队订餐餐厅",
        task="游客有素食/清真饮食要求，点餐时主动确认、协调专餐并讲解当地饮食文化",
        difficulty=1,
        category="文化礼仪",
        opening="团队午餐订的是当地特色农家菜。点菜前，你面前这位游客轻声提醒自己吃清真餐，还问桌上会不会有猪肉。",
        situation="你严格吃清真餐，看到菜单上都是本地风味，怕上桌的菜不合规又不好意思当众提，只能私下先跟导游确认。",
        stages=[
            SandboxStage(
                title="确认 · 提前登记",
                objective="点餐前主动询问全团饮食禁忌，登记素食/清真等特殊需求",
                guide_hint="发餐前逐一确认忌口与宗教饮食要求，登记后统一安排",
                kb_keywords=["饮食禁忌", "清真餐", "服务规范"],
                min_turns=1,
            ),
            SandboxStage(
                title="协调 · 专餐安排",
                objective="与餐厅协调为游客单独准备合规餐食，确保上桌无误",
                guide_hint="亲自向厨房说明清真要求（无猪肉/禽肉需清真屠宰等），确认餐具分开",
                kb_keywords=["餐饮协调", "宗教饮食", "细节服务"],
                min_turns=2,
            ),
            SandboxStage(
                title="讲解 · 饮食文化",
                objective="借机讲解当地饮食文化，让游客吃得明白、感到被尊重",
                guide_hint="介绍当地特色菜的由来与食材，讲清清真饮食背后的文化，增进交流",
                kb_keywords=["饮食文化", "跨文化交流", "讲解技巧"],
                min_turns=1,
            ),
        ],
        goals=[("服务意识", 1.3), ("文化知识", 1.1), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="哈桑", nationality="沙特阿拉伯", age="45", personality="温和稳重",
                preferences="严格清真饮食", quirks="会委婉确认食材来源",
                hidden="信仰虔诚，若餐食不合规会觉得被冒犯，需要被认真对待",
            ),
            CustomerProfile(
                name="小刘", nationality="中国", age="27", personality="新潮素食主义者",
                preferences="纯素食", quirks="会主动拍照记录菜品",
                hidden="担心被安排到蛋奶/荤油，希望导游理解「纯素」和「素食」的区别",
            ),
            CustomerProfile(
                name="法蒂玛", nationality="马来西亚", age="36", personality="随和开朗",
                preferences="习惯清真餐也吃中餐", quirks="会帮忙解释清真规则",
                hidden="希望导游尊重所有团友的饮食选择，不要区别对待",
            ),
        ],
    ),
    # ── 即兴讲解 · 遗产讲解 ──
    SandboxTemplate(
        template_id="t_great_wall",
        mode="narrate",
        title="长城讲解 · 八达岭",
        location="八达岭长城",
        task="向游客即兴讲解长城的历史沿革、军事功能与建筑智慧，并应答提问",
        difficulty=2,
        category="遗产讲解",
        opening="你们站在八达岭长城的垛口前，长城如巨龙蜿蜒于群山之巅。秋风猎猎，一位背着相机的游客望着远处，等你讲出第一句话。",
        situation="你第一次站上长城，被眼前的景象震撼，特别想了解这座伟大的工程是怎么建起来的，正期待导游的讲解。",
        stages=[
            SandboxStage(
                title="开场 · 气势先声",
                objective="用宏大的视角点出长城地位，瞬间抓住游客注意力",
                guide_hint="以「世界文化遗产」「万里长城」开场，先给震撼的画面感再讲细节",
                kb_keywords=["长城", "世界文化遗产", "开场讲解"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 历史与功能",
                objective="讲清长城修筑沿革、军事防御体系与建筑智慧",
                guide_hint="从秦代到明代的修筑史讲起，讲烽火台/敌楼/城墙结构的防御设计",
                kb_keywords=["长城历史", "军事防御", "古代建筑"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 互动升华",
                objective="回应「长城是否真的有用」「怎么修成的」等提问，升华精神内涵",
                guide_hint="用孟姜女/戍边故事增加温度，讲「不到长城非好汉」的民族精神",
                kb_keywords=["长城精神", "历史故事", "互动引导"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("互动引导", 1.1), ("沟通表达", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="大卫", nationality="美国", age="35", personality="好奇直率",
                preferences="喜欢宏大叙事", quirks="爱问「为什么」",
                hidden="想听长城背后的真实历史，而非背诵式的官方介绍",
            ),
            CustomerProfile(
                name="赵老师", nationality="中国", age="58", personality="沉稳博学",
                preferences="熟悉长城知识", quirks="会不动声色验证讲解准确性",
                hidden="在意讲解是否严谨，细节有误会暗自失望",
            ),
            CustomerProfile(
                name="卡米拉", nationality="西班牙", age="29", personality="感性浪漫",
                preferences="爱听传说故事", quirks="听到动人故事会眼睛发亮",
                hidden="希望讲解有情感共鸣，让她觉得「不虚此行」",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_forbidden_city",
        mode="narrate",
        title="故宫讲解 · 中轴礼制",
        location="故宫太和殿前",
        task="向游客讲解故宫的营建背景、中轴线礼制与建筑艺术，并应答提问",
        difficulty=2,
        category="遗产讲解",
        opening="你们穿过午门，站在太和殿前宽阔的广场上。琉璃瓦在阳光下泛着金光，游客们仰望着这座「天下第一殿」，等着你开口。",
        situation="你站在太和殿前的广场上，被故宫的宏大震撼，很好奇皇帝当年是怎么在这里上朝的，正等着导游讲解。",
        stages=[
            SandboxStage(
                title="开场 · 立起格局",
                objective="用「世界上最大的宫殿建筑群」立起故宫地位，引起兴趣",
                guide_hint="从午门→太和殿的空间体验切入，讲「中轴线」的礼制思想",
                kb_keywords=["故宫", "中轴线", "世界文化遗产"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 营建与礼制",
                objective="讲清故宫营建背景、等级礼制与建筑艺术",
                guide_hint="讲永乐迁都营建故宫、前朝后寝格局，太和殿的等级与功能",
                kb_keywords=["故宫历史", "礼制建筑", "太和殿"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 细节互动",
                objective="回应金砖/屋脊神兽/「9999间半」等细节追问，活跃气氛",
                guide_hint="用金砖墁地、脊兽数量等细节展示专业，鼓励游客找彩蛋",
                kb_keywords=["建筑细节", "屋脊兽", "互动讲解"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("互动引导", 1.2), ("沟通表达", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="陈阿姨", nationality="中国", age="62", personality="怀旧感慨",
                preferences="喜欢宫廷剧", quirks="会把电视剧情节带入提问",
                hidden="希望讲解能呼应她看过的宫廷剧，让知识变得亲切",
            ),
            CustomerProfile(
                name="卢卡斯", nationality="德国", age="40", personality="严谨细致",
                preferences="关注建筑构造", quirks="爱数柱子、问材料",
                hidden="想听到专业的建筑学视角，而不是泛泛的宫廷八卦",
            ),
            CustomerProfile(
                name="美琳", nationality="新加坡", age="25", personality="活泼爱拍照",
                preferences="故宫红墙打卡", quirks="会边听边查手机",
                hidden="想要「能发朋友圈」的讲解亮点和拍照建议",
            ),
        ],
    ),
    SandboxTemplate(
        template_id="t_terracotta",
        mode="narrate",
        title="兵马俑讲解 · 秦陵军阵",
        location="秦始皇兵马俑博物馆一号坑",
        task="向游客讲解兵马俑的发现、制作工艺与秦文化价值，并应答提问",
        difficulty=2,
        category="遗产讲解",
        opening="你们站在一号坑的观景台上，数千尊陶俑列阵而立，军容肃穆。一位游客轻声感叹「太震撼了」，随即回头期待地看着你。",
        situation="你被眼前的陶俑军阵震撼得说不出话，很想知道这些兵马俑是谁、为什么埋在这里，正等导游揭开谜底。",
        stages=[
            SandboxStage(
                title="开场 · 震撼先声",
                objective="用「世界第八大奇迹」与军阵气势开场，抓住游客",
                guide_hint="先让游客感受军阵的规模与震撼，再引出发现故事",
                kb_keywords=["兵马俑", "秦始皇陵", "世界第八大奇迹"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 发现与工艺",
                objective="讲清兵马俑的发现过程、烧制工艺与千人千面",
                guide_hint="讲1974年打井发现的故事，讲陶俑分段烧制、彩绘工艺与千人千面",
                kb_keywords=["兵马俑发现", "陶俑工艺", "秦文化"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 文明价值",
                objective="回应「为什么没有文字记载」「始皇为何修俑」等提问，升华文明价值",
                guide_hint="讲秦朝中央集权与陪葬制度，升华到中华文明的高度",
                kb_keywords=["秦始皇", "陪葬制度", "中华文明"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("互动引导", 1.1), ("沟通表达", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="安德森", nationality="英国", age="49", personality="历史迷，见多识广",
                preferences="读过大量中国历史", quirks="会引经据典追问",
                hidden="想听到有深度的考古细节，浅层讲解会让他失望",
            ),
            CustomerProfile(
                name="文文", nationality="中国", age="22", personality="大学生，求知欲强",
                preferences="喜欢短视频知识", quirks="边听边录vlog",
                hidden="希望讲解有金句可剪进视频，也真心想学知识",
            ),
            CustomerProfile(
                name="铃木", nationality="日本", age="55", personality="安静认真",
                preferences="对东亚文明感兴趣", quirks="会认真做笔记",
                hidden="期待听到秦文化与东亚文明的关联，希望讲解有体系",
            ),
        ],
    ),
    # ── 即兴讲解 · 风貌讲解 ──
    SandboxTemplate(
        template_id="t_west_lake",
        mode="narrate",
        title="西湖讲解 · 十景人文",
        location="西湖苏堤",
        task="向游客讲解西湖的山水格局、十景传说与人文积淀，并即兴应答",
        difficulty=1,
        category="风貌讲解",
        opening="你们漫步苏堤，垂柳拂水、湖光潋滟，远山如黛。一只画舫缓缓划过湖面，游客们举着手机，等你把这方山水讲活。",
        situation="你走在苏堤上，觉得西湖美得像一幅画，很想知道这里都有什么故事，正期待导游把风景讲出韵味。",
        stages=[
            SandboxStage(
                title="开场 · 山水入画",
                objective="用诗意的语言点出西湖格局，让游客进入意境",
                guide_hint="以「欲把西湖比西子」开场，讲山环水抱的格局之美",
                kb_keywords=["西湖", "苏堤", "山水格局"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 十景与传说",
                objective="讲西湖十景与白蛇传等传说，让景观有故事",
                guide_hint="讲苏堤春晓/断桥残雪等十景，穿插白蛇传、东坡筑堤的传说",
                kb_keywords=["西湖十景", "白蛇传", "苏轼"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 人文升华",
                objective="回应游客对诗词/历史名人的兴趣，升华西湖人文价值",
                guide_hint="从白居易、苏东坡治理西湖讲到「人间天堂」，鼓励游客吟诗互动",
                kb_keywords=["西湖人文", "诗词文化", "互动引导"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.3), ("沟通表达", 1.2), ("互动引导", 1.1)],
        customer_pool=[
            CustomerProfile(
                name="吴女士", nationality="中国", age="54", personality="优雅文艺",
                preferences="喜欢诗词楹联", quirks="会轻声背诵相关诗句",
                hidden="希望讲解能接得住诗词，遇到知音会格外开心",
            ),
            CustomerProfile(
                name="索菲亚", nationality="希腊", age="31", personality="浪漫爱美",
                preferences="喜欢传说故事", quirks="会问「哪个季节最美」",
                hidden="想拍出梦幻的照片，希望导游推荐最佳机位与时段",
            ),
            CustomerProfile(
                name="阿凯", nationality="中国", age="26", personality="直爽爱玩",
                preferences="喜欢看热闹", quirks="爱开「许仙白娘子」玩笑",
                hidden="想要轻松有趣的讲解，别太文绉绉",
            ),
        ],
    ),
    # ── 即兴讲解 · 主题讲解 ──
    SandboxTemplate(
        template_id="t_chinese_garden",
        mode="narrate",
        title="古典园林 · 造园意境",
        location="苏州拙政园",
        task="向游客讲解中国古典园林的造园手法、审美意境与人文内涵，并应答提问",
        difficulty=2,
        category="主题讲解",
        opening="你们走进拙政园，太湖石瘦漏透皱，曲径通幽处忽见一池碧水。一位游客看着窗框外的景致，好奇地问「这窗子怎么像一幅画？」",
        situation="你第一次逛中国园林，觉得处处都像画一样，对「窗子框景」的讲究很好奇，正等导游讲讲园林的门道。",
        stages=[
            SandboxStage(
                title="开场 · 意境导入",
                objective="用「咫尺山林」的造园理念开场，让游客理解园林是立体的画",
                guide_hint="从「移步换景」的体验切入，讲园林「虽由人作，宛自天开」",
                kb_keywords=["苏州园林", "造园理念", "移步换景"],
                min_turns=1,
            ),
            SandboxStage(
                title="讲解 · 造园手法",
                objective="讲透借景、框景、漏景、障景等经典造园手法",
                guide_hint="结合实地讲借景（远借塔影）、框景（窗为画框）、太湖石的瘦漏透皱",
                kb_keywords=["借景", "太湖石", "园林建筑"],
                min_turns=2,
            ),
            SandboxStage(
                title="应答 · 人文内涵",
                objective="回应园林主人、文人精神等提问，升华园林文化",
                guide_hint="讲园主避世隐逸的心境，讲文人园林的诗画精神与生活美学",
                kb_keywords=["文人园林", "隐逸文化", "生活美学"],
                min_turns=2,
            ),
        ],
        goals=[("文化知识", 1.4), ("沟通表达", 1.2), ("互动引导", 1.0)],
        customer_pool=[
            CustomerProfile(
                name="沈先生", nationality="中国", age="60", personality="清雅沉静",
                preferences="痴迷园林与书画", quirks="会站在某处静静端详很久",
                hidden="期待讲解触及园林与文人精神的深层关联",
            ),
            CustomerProfile(
                name="埃玛", nationality="荷兰", age="36", personality="理性好奇",
                preferences="关注设计美学", quirks="会对比西方园林提问",
                hidden="想弄清中国园林与西方几何式园林的本质差异",
            ),
            CustomerProfile(
                name="团团", nationality="中国", age="23", personality="活泼爱拍照",
                preferences="汉服爱好者", quirks="穿着汉服四处找机位",
                hidden="想听园林的美学讲解配合拍照，也喜欢「穿越感」的故事",
            ),
        ],
    ),
    # ── 路线带团 ──
]

# 类别 → 中文说明（供前端分类展示）
TEMPLATE_CATEGORIES: dict[str, str] = {
    "入境定制游全流程实战": "行前 · 行中 · 行后 入境定制游全流程实战",
    "应急处置": "突发状况处理（火灾/疾病/证件遗失/恶劣天气等）",
    "文化礼仪": "跨文化礼仪与宗教禁忌",
    "接待服务": "接机、入住等接待流程与服务",
    "服务规范": "旅游服务规范与纠纷处理",
    "特殊游客": "老年、亲子等特殊群体游客服务",
    "遗产讲解": "世界文化遗产与历史遗迹讲解",
    "风貌讲解": "城市风貌与山水格局讲解",
    "主题讲解": "专题主题（园林等）深度讲解",
    "带团实战": "多站点路线带团实战",
}
